### ISSUE TITLE
Fails when not installing globally

### ISSUE THREAD

**Issue by jonnor** [ConsenSys/truffle#101]
```
npm install truffle
[jon@jon-laptop dapp]$ ./node_modules/.bin/truffle init
./node_modules/.bin/truffle: line 19: cd: /usr/lib/node_modules/truffle/: No such file or directory
./node_modules/.bin/truffle: line 20: /usr/lib/node_modules/truffle//node_modules/.bin/babel-node: No such file or directory
```
This makes it hard to install without root privileges, and tricky for developers to ensure they are on the same version. It also requires extra setup in Travis CI, cause `npm install` won't pull it in anymore.

**Comment by jonnor** [comment]
Looked into the `truffle` script which has those hardcoding, and instead did the equivalent. However it fails with some ES6/babel things:

```
[jon@jon-laptop dapp]$ ./node_modules/truffle/node_modules/.bin/babel-node ./node_modules/truffle/truffle.es6 
/home/jon/work/thegrid/dapp/node_modules/truffle/lib/config.es6:195
    config.expect = function(expected_path, description="file", extra="", callback) {
SyntaxError: Unexpected token =
  at exports.runInThisContext (vm.js:53:16)
  at Module._extensions..js (module.js:417:10)
  at Object.require.extensions.(anonymous function) [as .es6] (/home/jon/work/thegrid/dapp/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
  at Module.load (/home/jon/work/thegrid/dapp/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
```

This on nodejs 4.2

**Comment by tcoulter** [comment]
Hi @jonnor. I'm currently in the process of revamping the scripts that get run, mostly for windows support, but it'll result in better organization and portability in the long run. Can you do this for me:

First, pull from the `windows` branch and install locally:

```
$ git clone https://github.com/ConsenSys/truffle.git
$ cd truffle
$ git checkout windows
$ npm install
```

Then, try running truffle through the new `cli.js`:

```
(in truffle dir)
$ node cli.js <options>
```

Does that work for you? My guess is it should. Let me know -- I expect this to be pushed to master in days.

**Comment by jonnor** [comment]
I fixed it by adding a `./truffle` wrapper to my project (included below), inspired by the original truffle shell script. This works for now, can try to remove when you've pushed the portability fixes master / released it.

```
#!/bin/bash

# Replicated from truffle bash script to work with non-global NPM install
# See https://github.com/ConsenSys/truffle/issues/101
export TRUFFLE_WORKING_DIRECTORY=`pwd`;
export TRUFFLE_NPM_LOCATION=`pwd`/node_modules/truffle;

# Hack. babel-node will clobber -e, and it doesn't look like `--` will stop it.
# Because we're doing string replacement, we have to take edge cases into account.
args=" $@"
args=${args// -e / --environment }
args=${args// -e=/ --environment=}
args=${args// -environment/ --environment}

cd ${TRUFFLE_NPM_LOCATION}
./node_modules/.bin/babel-node ./truffle.es6 -- ${args}
```

**Comment by tcoulter** [comment]
@jonnor I just tried, and this is fixed on master. A script shows up at `./node_modules/.bin/truffle` when installed locally, and it seemed to work for me. Will close this -- although master hasn't been released to npm yet. Please reopen if you continue to encounter issues.
