### ISSUE TITLE
truffle test returns 0 statuscode on failing tests

### ISSUE THREAD

**Issue by jonnor** [ConsenSys/truffle#102]
This breaks continious integration usecases. Which is a dealbreaker for orgs/teams doing continous deployment (autodeploy when tests pass).

Standard for mocha runners is to return the number of failing tests. But anything non-zero would be fine.

This may be caused by `babel-node` executable, so this may be fixed by #80 and/or the changes due to Windows support (#81).

**Comment by jonnor** [comment]
Considering the impact of such behavior, I would heavily recommend an automated test which ensures the correct behavior.

**Comment by tcoulter** [comment]
Fixed on master. Cheers!
