### ISSUE TITLE
' truffle serve ' success, but the localhost:8080 show error!

### ISSUE THREAD

**Issue by YyItRoad** [ConsenSys/truffle#108]
show alert("There was an error fetching your accounts.").  but truffle test is success.

**Comment by tcoulter** [comment]
Do you have an Ethereum client running? 

Please check out the documentation here: http://truffle.readthedocs.org

Please reopen if this doesn't fix your issue. Thanks!

**Comment by grubby8** [comment]
@YyItRoad I have got the same problem,how you sovle it?

**Comment by diogocortiz** [comment]
Getting the same problem. I am using testrpc. Did you solve tis problem?

**Comment by tcoulter** [comment]
Did you guys run `truffle migrate` before running `truffle serve`? You need to deploy your contracts first before you can have a website that interacts with them.

**Comment by diogocortiz** [comment]
Yes, I did. I have tried again just to make sure i followed those steps and got the same error msg. Any clue?

**Comment by diogocortiz** [comment]
I have installed the envionment in a server in c9.io. I am accessing the web page using a remote browser. Could this be the problem (the browser could not load the credentials)?

**Comment by RunshanHu** [comment]
Getting the same problem. I'm using a remote virtual machine to developing the dapp and trying to access the website by local browser. Could this be the reason?

**Comment by blackbutler756** [comment]
facing error with : 

```
>truffle serve 

Serving static assets in ./build on port 8080...
/usr/lib/node_modules/truffle/build/cli.bundled.js:124978
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (/usr/lib/node_modules/truffle/build/cli.bundled.js:124978:11)
    at setFSEventsListener (/usr/lib/node_modules/truffle/build/cli.bundled.js:125032:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/usr/lib/node_modules/truffle/build/cli.bundled.js:125196:16)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:125330:25)
    at LOOP (fs.js:1773:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I used webpack

**Comment by 3th3r3um** [comment]
Same issue for me on arch:

> mkdir FsEventsError
> truffle init
> truffle migrate
> truffle serve
Serving static assets in ./build on port 8080...
/usr/lib/node_modules/truffle/build/cli.bundled.js:138158
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (/usr/lib/node_modules/truffle/build/cli.bundled.js:138158:11)
    at setFSEventsListener (/usr/lib/node_modules/truffle/build/cli.bundled.js:138212:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/usr/lib/node_modules/truffle/build/cli.bundled.js:138376:16)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:138510:25)
    at gotStat (fs.js:1783:21)
    at FSReqWrap.oncomplete (fs.js:152:21)

System Info:
kernel: x86_64 Linux 4.11.9-1-ARCH
I'm running testrpc in a different terminal
node v8.2.1
npm 5.3.0

**Comment by guisantos** [comment]
Same issue here. Using testrpc
![image](https://user-images.githubusercontent.com/14335913/33126731-b7a313f8-cf6c-11e7-84b4-1d04a9b5ba68.png)

**Comment by githubmilind** [comment]
getting same error on Windows 10. Please help

**Comment by gengxuelei** [comment]
You need modify some files as this:
https://gengxuelei.github.io/2017/12/26/truffle%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97/

modify`package.json`：
```
"dev": "webpack-dev-server --host 0.0.0.0 --port 8080"
```

modify`truffle.js`：
```
development: {
  host: 'yourIp',
  port: 8545,
  network_id: '*' // Match any network id
}
```

modify`app/javascripts/app.js`：
change：
~~window.web3 = new Web3(new Web3.providers.HttpProvider("http://127.0.0.1:9545"));~~
to：
```
window.web3 = new Web3(new Web3.providers.HttpProvider("http://yourIp:8545"));
```

substitute `npm run dev `  for `truffle server`：
```
npm run dev
```

**`fsevents` error need use webpack box & substitute `npm run dev `  for `truffle server`**

**Comment by spnzig** [comment]
@gengxuelei I followed the changes that you mentioned and changed the files (package.json, truffle.js and app.js) . However I still get the same issue. Am I missing anything?
