### ISSUE TITLE
[Docs] The searching keyword is not working.

### ISSUE THREAD

**Issue by u2** [ConsenSys/truffle#112]

**Comment by tcoulter** [comment]
Doc searching is provided free by the web host, readthedocs.org. I tried it last night while on mobile and it didn't appear to be working. However, this morning, search appears to be working fine. 

<img width="1440" alt="screen shot 2016-03-18 at 8 12 55 am" src="https://cloud.githubusercontent.com/assets/92629/13882163/7eeedc28-ece1-11e5-8a6d-587b7157a609.png">

If your problem persists please contact readthedocs.org. Thanks!

**Comment by u2** [comment]
I can see this page also, but while you click the result link, it will jump to a error page, and the url is [http://truffle.readthedocs.org/en/latest/README/?highlight=web3](http://truffle.readthedocs.org/en/latest/README/?highlight=web3.)
Before I used solidity.readthedocs.org, the search result page url was something like this [https://solidity.readthedocs.org/en/latest/search.html?q=web3&check_keywords=yes&area=default](https://solidity.readthedocs.org/en/latest/search.html?q=web3&check_keywords=yes&area=default) I guessed the same format should be workable for truffle, so I tried [https://truffle.readthedocs.org/en/latest/search.html?q=web3&check_keywords=yes&area=default](https://truffle.readthedocs.org/en/latest/search.html?q=web3&check_keywords=yes&area=default), I worked well.So there is something wrong.
