### ISSUE TITLE
can be better to change the error message from "TypeError: Cannot read property 'bytecode' of undefined" to "Error: File name and Contract name not matched"

### ISSUE THREAD

**Issue by TOMOAKI12345** [ConsenSys/truffle#113]
https://gyazo.com/c4b53eac5846aa9801168356dca0659d

**Comment by tcoulter** [comment]
Thanks @TOMOAKI12345. This has already been fixed in the 0.4.0 pre-release. Please try that instead!

https://github.com/ConsenSys/truffle/releases/tag/v0.3.9

**Comment by TOMOAKI12345** [comment]
thanks now "Could not find expected contract or library in 'MetaCoin.sol': contract or library 'MetaCoin' not found." 
and can run by -p https://gyazo.com/89046c8627f9df092ed82a1400c22814

p.s. For my Mac yosemite env 
$ mv /usr/local/bin/truffle {somewhere}
$ mv /usr/local/bin/truffle-exec {somewhere}
needed
