### ISSUE TITLE
dockerize truffle

### ISSUE THREAD

**Issue by hermanjunge** [ConsenSys/truffle#114]
Let's dockerize truffle. The developer mounts their files into the container everytime they run a command using `make`. Not so crazy, is not only popular in the circles this poster hangs around, but they built a whole infrastructure that way in deis ([example](https://github.com/deis/router/blob/master/Makefile), [example](https://github.com/deis/controller/blob/master/Makefile)).

I'm taking this task over, of course.

**Comment by jtremback** [comment]
Why?

**Comment by hermanjunge** [comment]
I don' want to install anything in my machine, except _docker_

**Comment by hermanjunge** [comment]
PR #134
