### ISSUE TITLE
truffle create:contract fails with Reference error

### ISSUE THREAD

**Issue by davebryson** [ConsenSys/truffle#115]
I'm using version 0.3.10.  When you run `truffle create:contract Hello`  the command fails with:

`ReferenceError: Create is not defined`

I believe the problem is here:

https://github.com/ConsenSys/truffle/blob/master/cli.js#L158

Create is not explicitly imported into the cli.  It looks like an easy fix. Instead of  `Create.create()` it should be `Truffle.create.create()`.  The same is true for `create:test`

**Comment by tcoulter** [comment]
Good catch. Will fix today.

**Comment by tcoulter** [comment]
Fixed on master. Thanks again.

**Comment by davebryson** [comment]
Thank you for Truffle!

**Comment by tcoulter** [comment]
:) You're welcome.
