### ISSUE TITLE
Truffle tries to compile all files in /contracts/

### ISSUE THREAD

**Issue by kumavis** [ConsenSys/truffle#119]
Vim creates temporary files e.g. `.swp` in the working directory.

:crying_cat_face:

**Comment by tcoulter** [comment]
Hmm, I thought I fixed this. Are you on master?

**Comment by tcoulter** [comment]
This line should be filtering out any files that don't end in `.sol` or files that start with a `.`: https://github.com/ConsenSys/truffle/blob/master/lib/config.js#L241

If you're on master and still seeing this behavior, will reopen, and we should debug when you have time.

**Comment by kumavis** [comment]
this fix must not have been published - my students are using the latest published version

**Comment by kumavis** [comment]
but used the opportunity to show people how to file issues in github
