### ISSUE TITLE
Specify which contracts should be deployed for each test

### ISSUE THREAD

**Issue by oed** [ConsenSys/truffle#12]
Right now all contracts are redeployed before each separate testfile is run. If you where able to specify which contracts that should be deployed before each test it would speed up the testing process.
This could be specified in the top of the testfile, stating which contracts that should be deployed.

**Comment by tcoulter** [comment]
Closing because this is old. All contracts are redeployed for each test, but they are only compiled once. I recommend using something like eth-testrpc or ethersim to increase speed.
