### ISSUE TITLE
Truffle won't run on Windows7 - "The system cannot find the path specified."

### ISSUE THREAD

**Issue by wdudek** [ConsenSys/truffle#122]
Hello.  The install via npm seems to have worked fine, but when I type in "truffle" in a windows command prompt, all I get is:
`The system cannot find the path specified.`

**Comment by tcoulter** [comment]
This will be fixed with the imminent release Truffle v1.0.0 next week. In the mean time, use the v0.4.0 pre-release (which will be turning into v1.0.0) which does work! Cheers! https://github.com/ConsenSys/truffle/releases
