### ISSUE TITLE
Add "alreadydeployed" to truffle.json so that one can choose which contracts to deploy or not

### ISSUE THREAD

**Issue by brainframe-me** [ConsenSys/truffle#124]
If I have 3 contracts that are deployed in prod with truffle, and I only want to modify 1 contract and redeploy it so that it creates a complete new contract address. How can I then make sure that the build does not change the other 2 (non-changed) contracts? If I remove the 2 already deployed contracts from the truffle.json/deploy, then it effectively skips redeploying which is already good, and it seems to keep the old generated .sol.js files in the build which still refers to the old adresses, which is great. Unfortunately the newly generated app.js now returns "undefined" when calling "OneOf2NotRedeployedContracts.deployed()", and only the newly deployed contract works.
It would be great if there was a "alreadydeployed" similar like "deploy" in truffle.json, which would to specify which contracts should not be redeployed but which would allow a correct build + refer to the correct previously generated .sol.js files with the old adresses. Or is this already possible in another way?

**Comment by tcoulter** [comment]
Thanks for reporting this. This feature has been subsumed into Truffle 2.0's migrations feature, where you can decide which contracts get deployed using code. Give it a shot if you haven't already! Cheers!
