### ISSUE TITLE
truffle deploy is much more optimized than solc --optimize --bin {some_source.sol}? 

### ISSUE THREAD

**Issue by TOMOAKI12345** [ConsenSys/truffle#125]
contract ConsultingHalf {
    /*
     *  This contract accepts payment from clients, and payout to engineer and manager.
     */
    address public engineer;
    address public manager;
    uint public createdTime;
    uint public updatedTime;

    function ConsultingHalf(address _engineer, address _manager) {
        engineer = _engineer;
        manager = _manager;
        createdTime = block.timestamp;
        updatedTime = block.timestamp;
    }

    /* Contract payout hald */
    function payout() returns (bool _success) {
        if(msg.sender == engineer || msg.sender == manager) {
             engineer.send(this.balance / 2);
             manager.send(this.balance);
             updatedTime = block.timestamp;
             _success = true;
        }else{
            _success = false;
        }
    }
}

// when I deploy from 
$truffle test test/ConsultingHalf.js
// then the deployed binary code is 
$ eth.getCode("0xeae16da8c4fcf18ccc69f09c0e8258233e931e82")
"0x606060405260e060020a600035046343bdfb728114610047578063481c6a7514610050578063603a552e1461006257806363bd1d4a14610074578063b2f4bdb014610102575b005b61010b60035481565b61011d600154600160a060020a031681565b61011d600054600160a060020a031681565b61010b6000805433600160a060020a03908116911614806100a45750600154600160a060020a0390811633909116145b15610130578054600160a060020a039081169082906002309091163104606082818181858883f15050600154604051600160a060020a0391821694503090911631915082818181858883f15050426003555060019250610130915050565b61010b60025481565b60408051918252519081900360200190f35b600160a060020a03166060908152602090f35b9056"

// but if we do from solc compile, 
$ solc --optimize --bin contracts/ConsultingHalf.sol 
6060604081815280610180833960a090525160805160008054600160a060020a03199081168417909155600180549091168217905542600281905560035550506101338061004d6000396000f3606060405260e060020a600035046343bdfb728114610047578063481c6a7514610050578063603a552e1461006257806363bd1d4a14610074578063b2f4bdb014610102575b005b61010b60035481565b61011d600154600160a060020a031681565b61011d600054600160a060020a031681565b61010b6000805433600160a060020a03908116911614806100a45750600154600160a060020a0390811633909116145b15610130578054600160a060020a039081169082906002309091163104606082818181858883f15050600154604051600160a060020a0391821694503090911631915082818181858883f15050426003555060019250610130915050565b61010b60025481565b60408051918252519081900360200190f35b600160a060020a03166060908152602090f35b9056

Why the difference is happening ?

**Comment by tcoulter** [comment]
Not sure. Unfortunately I don't believe this to be a Truffle issue. Truffle is using the solc library provided on npm. My only guess is that your version and the version of solc in Truffle (v0.2.x) are different.

Going to close because I don't think there's anything we can do.
