### ISSUE TITLE
function declaration error in truffle/lib/contracts.js

### ISSUE THREAD

**Issue by it4ch1** [ConsenSys/truffle#132]
Hello, the execution of fruffle 1.0.1 fails due to  a syntax error in the declaration of update_sources function (truffle/lib/contracts.js:41)
`update_sources(config, callback) {`
I solved the issue changing it in:
`update_sources: function(config, callback) {`

**Comment by austing** [comment]
Same issue.
Looks like the rest of the file was recently changed from the first format to the second, but update_sources was left out.

**Comment by tcoulter** [comment]
Whoops, fixed. Give it another shot - should be updated now to `1.0.2`. 

If this still doesn't work, I'd love to know the error, and feel free to reopen this ticket. That said, upgrading to node 5.0 should solve your issues as well. Cheers!
