### ISSUE TITLE
Truffle can't find contract outside of `contracts` directory

### ISSUE THREAD

**Issue by tcoulter** [ConsenSys/truffle#141]
If you import a contract that lives outside of the `contracts` directory, Truffle will have trouble finding it.

**Comment by thiagodelgado111** [comment]
That would be good to create mock contracts or tests contracts without the need to put them into the same folder as other contracts. Currently I'm running a few tests using contracts that I created just to test something very specific and currently I have a grunt task to copy them to contracts folder and remove them after running those tests

**Comment by tcoulter** [comment]
Marked as a bug. Need to verify on Truffle 2.0.
