### ISSUE TITLE
Get past events return nothing

### ISSUE THREAD

**Issue by louptheron** [ConsenSys/truffle#142]
I would like to retrieve a specific event : 
```
var membershipRequestEvent = insuranceInstance.MembershipRequest(null, {fromBlock: 0, toBlock: 'latest'});
membershipRequestEvent.get(function(error, unconfirmedInsurers){
  if(!error)
    console.log(unconfirmedInsurers);
  })
});
```
It return an empty array, and a know this event is there, because I was watching for him we he was sent by using : 
```
var event = insuranceInstance.MembershipRequest(null, {fromBlock: 0, toBlock: 'latest'}, function(err, res){
  if(!err)
    console.log(res);
});
```

So watching for a event work fine, but retrieve past events fail, any idea ?

Thank you

**Comment by louptheron** [comment]
In fact, I was using `testrpc`, with does not return events ; by using `geth` it does work as expected.

**Comment by ayushgupta0610** [comment]
Hi @louptheron , can you kindly help me understand how did you resolve this issue?
