### ISSUE TITLE
Suspected transaction OOG error never thrown and tx never rolled back

### ISSUE THREAD

**Issue by elenadimitrova** [ConsenSys/truffle#145]
Creating a contract where a suspected transation OOG error occurs but is never thrown and transaction never rolled back.
In our case this results in a bytes32 -> address mapping being populated with an odd Contract address of format [0x74696f6e5f544553540000000000000000000000] which appears to be formed from the post 8 chars of the byte32 key with which we try to create it instead of the contract address itself. Also no OOG error is thrown.
Code sample here:
https://github.com/elenadimitrova/ContractFactory

**Comment by elenadimitrova** [comment]
@area has worked out that Truffle by default only sends 3141592 gas, which isn't enough to deploy the contract in question. We can override this by raising the gas value in truffle.json "gas": 4000000 (we went with just under homestead limit)

testrpc 2.0.7 now has the Homestead gas limit which also helps

**Comment by tcoulter** [comment]
Hi @elanadimitrova. I apologize for not responding to this. It appears you were able to fix the issue, so I'm going to close this (especially with Truffle 2.0.4, this should be working just fine). Let me know if you run into this issue again. Thanks!
