### ISSUE TITLE
truffle init is not working out of the box.

### ISSUE THREAD

**Issue by bjrenfrow** [ConsenSys/truffle#155]
C:\Users\bjren\dev\eth: `npm install -g truffle`
C:\Users\bjren\dev\eth: `truffle init`
Couldn't find any suitable environment. Check environment configuration.
C:\Users\bjren\dev\eth: `echo %NODE_ENV%`
development

On Windows 10 using commander

**Comment by python4d** [comment]
+1

**Comment by mttkay** [comment]
This is frustrating, since when running through [the tutorial](http://truffle.readthedocs.io/en/latest/getting_started/compile/) and following the instructions, it's unclear what is missing.

**Comment by mttkay** [comment]
Possibly related: https://github.com/ConsenSys/truffle/issues/137

**Comment by tcoulter** [comment]
It's because NODE_ENV is set. If you unset NODE_ENV it should work correctly.

This will be fixed in the next version.

**Comment by mttkay** [comment]
I `unset NODE_ENV`, and I'm still getting the same error.

**Comment by mttkay** [comment]
Ah--the trick is to run `truffle init` again after unsetting NODE_ENV. Now it compiles fine. 👍

**Comment by pev115** [comment]
how do you unset NODE_ENV?!

**Comment by tcoulter** [comment]
Closing for housekeeping purposes. If you still have issues don't hesitate to let me know!
