### ISSUE TITLE
Enhancement: Better way to test enums

### ISSUE THREAD

**Issue by raineorshine** [ConsenSys/truffle#157]
Unless there is a global available to tests that I am not aware of, enums are only understood as `uint` types (as they are compiled to):

```
it('should have a myEnum property', () => {
  var contract = MyContract.deployed()
  return contract.myEnum.call(accounts[0]).then(myEnumResult => {
    assert.equal(myEnumResult.valueOf(), 1)
  })
})
```

It would be better to have something like this so that the test was not tightly coupled to the enum's underlying integer values:

```
assert.equal(myEnumResult.valueOf(), contract.deployed().MyEnum.SomeValue)
```

Is this feasible? Would you have to parse the Solidity yourself since the deployed contract just treats enums as uint's?

**Comment by tcoulter** [comment]
Likely feasible if the enums are described in the contract's ABI. This would be a feature update for ether-pudding, however.

**Comment by sebs** [comment]
not like a on spot answer,[but chai-as-promised](https://gist.github.com/sebs/74e47e8fba988aaacdf31f868ca8467a) improved it for me 

2 highlights

* .eventually does the valueOf
* the before does the setup on a way to obstruct the first then.
