### ISSUE TITLE
What's the recommended way to test a contract with constructor params?

### ISSUE THREAD

**Issue by raineorshine** [ConsenSys/truffle#159]
I understand that truffle's deploy and test flow intentionally do not support contracts with parameters. It seems like this would still be double with a custom exec script. I am going to need be able to unit test the constructor for my contract since it is an important part of the dapp's overall functionality. Could you provide a basic example of how one might approach this, or give some suggestions for someone relatively new to Solidity/Truffle development? Thank you!

**Comment by tcoulter** [comment]
Hey @raineorshine,

I apologize for not responding to this. The way I do it is to have the test set up a new version of the contract using `MyContract.new()`, passing constructor parameters, then I write tests against that contract using further transactions and calls. Let me know if you need a code example, and I can provide one. 

Closing for housekeeping, but I hope I helped (even though my response was way late!). Thanks!

**Comment by raineorshine** [comment]
Okay, thank you!

**Comment by danielyaa5** [comment]
How can I send payment to the constructor?

**Comment by FollowJack** [comment]
@tcoulter can you provide some code. Thanks in advance :)

**Comment by stefek99** [comment]
Example: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/crowdsale/Crowdsale.test.js

![image](https://user-images.githubusercontent.com/249703/38312482-e596520c-37ef-11e8-8249-2b76b1c66ee9.png)
