### ISSUE TITLE
Exception 'new BigNumber() not a base 16 number' being raised after a unit test fails

### ISSUE THREAD

**Issue by thiagodelgado111** [ConsenSys/truffle#160]
### Truffle and OS info
Mac OS X 10.11.4
Truffle v1.0.3 

### Expected behavior
The test fails and if there are logs to show, truffle print them out in console

### Actual behavior
Truffle crashes and print out the stacktrace below for what it seemingly is a web3 problem.
 
### Stacktrace
> /home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/truffle/node_modules/solc/bin/soljson-latest.js:1
> (function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename
> BigNumber Error: new BigNumber() not a base 16 number: 
    at raise (/home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/truffle/node_modules/web3/node_modules/bignumber.js/bignumber.js:1177:25)
>     at /home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/truffle/node_modules/web3/node_modules/bignumber.js/bignumber.js:1165:33
>     at new BigNumber (/home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/truffle/node_modules/web3/node_modules/bignumber.js/bignumber.js:212:28)
>     at [object Object].formatOutputString [as _outputFormatter] (/home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/truffle/node_modules/web3/lib/solidity/formatters.js:217:19)
>     at /home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/truffle/node_modules/web3/lib/solidity/type.js:237:25
>     at [object Object].SolidityType.decode (/home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/truffle/node_modules/web3/lib/solidity/type.js:238:11)
>     at /home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/truffle/node_modules/web3/lib/solidity/coder.js:219:29
>     at Array.map (native)
>     at [object Object].SolidityCoder.decodeParams (/home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/truffle/node_modules/web3/lib/solidity/coder.js:218:26)

### How to reproduce
Run `truffle test` with a unit test where the TX fails without raising events.

### Details
I've tested it using web3.js 0.16.0 and it seems to print out the "Events emitted" message with no events, but it doesn't crash anymore. Testing against TestRPC it works.

**Comment by anrodon** [comment]
Same problem here.

**Comment by tcoulter** [comment]
Hi @thiagodelgado111, I suspect this is an issue with what you're passing to a contract function that expects a BigNumber. It's hard to tell without code however.

Since this was on Truffle 1.0, can you upgrade to Truffle 2.0 and tell me if you still have the issue? I'm going to close this issue for housekeeping reasons but please reopen and command if you have issues. Thanks!
