### ISSUE TITLE
Can't access abstract contract object when requiring MyContract.sol.js

### ISSUE THREAD

**Issue by raineorshine** [ConsenSys/truffle#169]
Hi. I am trying to use a [custom build process](http://truffle.readthedocs.io/en/latest/advanced/build_processes/) but I am having difficulty accessing the contract object after the load in order to call `new`.

This is what I have working so far:

```js
const Pudding = require('ether-pudding')
const MyContract = require('../environments/development/contracts/MyContract.sol.js')
MyContract.load(Pudding)
```

When I try to run `MyContract.new({ from: web3.eth.accounts[0] })` I get:

```sh
TypeError: Cannot read property 'apply' of undefined
    at Function.Contract.new (../environments/development/contracts/MyContract.sol.js:38:32)
```

Which is this code:

```
  Contract.new = function() {
    if (Contract.Pudding == null) {
      throw new Error("MyContract error: Please call load() first before calling new().");
    }

    // Error occurs here, stating that 'new' is undefined
    return Contract.Pudding.new.apply(Contract, arguments);
  };
```

What am I missing?

**Comment by raineorshine** [comment]
@tcoulter I'm sure you are busy. This is currently blocking progress for me. Any help is appreciated!

**Comment by andylockran** [comment]
I think you need to create a new contract object, at the moment you're just referencing a contract definition:

Can you share the source to the two files?

**Comment by tcoulter** [comment]
First check if the `.sol.js` file has a binary in it. Also, which version of Truffle are you using, and which version of ether-pudding are you using? Pudding just came out with a 3.0 release and Truffle hasn't been updated yet, so you might be seeing a version mismatch. Truffle uses 2.x at the moment.

**Comment by raineorshine** [comment]
@tcoulter The `.sol.js` does have a binary in it.

I'm using truffle v1.0.2 and ether-pudding v3.0.3.

I will try it with ether-pudding v2.x. 

@andylockran The contract object comes will be provided by the `new` function, but that is what is failing currently.

**Comment by raineorshine** [comment]
Problem solved when I switched to ether-pudding v2.x. Thanks!

**Comment by tcoulter** [comment]
👏
