### ISSUE TITLE
npm install -g truffle, errors!!!

### ISSUE THREAD

**Issue by lin520chong** [ConsenSys/truffle#170]
5548 error error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/truffle/node_modules/lodash'
5548 error error rolling back  truffle@1.0.3 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/truffle/node_modules/lodash']
5548 error error rolling back   errno: 53,
5548 error error rolling back   code: 'ENOTEMPTY',
5548 error error rolling back   path: '/usr/local/lib/node_modules/truffle/node_modules/lodash' }
5549 error not found: git
5550 error Failed using git.
5550 error This is most likely not a problem with npm itself.
5550 error Please check if you have git installed and in your PATH.
5551 error System Linux 2.6.32.43-tlinux-1.0.1-default
5552 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "truffle"
5553 error cwd /home/marvin/demo
5554 error node -v v0.10.24
5555 error npm -v 1.3.21
5556 error code ENOGIT
5557 verbose exit [ 1, true ]

**Comment by tcoulter** [comment]
It looks like from that error message you don't have git installed. Install
git first.

**Comment by tcoulter** [comment]
Closing. Let me know if you're still having an issue.
