### ISSUE TITLE
Truffle.js config issue - app.js not complete after serve call

### ISSUE THREAD

**Issue by nwootton** [ConsenSys/truffle#177]
I am learning Truffle by using the [Conference](https://github.com/eshon/conference) example from Eva Shon.  

Changing the Truffle build path for the app.js file in the top level truffle.js config appears to cause the resulting app.js in the build directory to be incomplete and then throw errors when used.

Using 
```js
"app.js": [ "javascripts/app.js", "javascripts/hooked-web3-provider.min.js"]
```
works fine, but using
```js
"js/app.js": [ "javascripts/app.js", "javascripts/hooked-web3-provider.min.js"]
```

results in a much smaller file that is missing the bluebird capabilities. The messages in the console still say that the code has been compiled without issue.

```console
Using environment development.
Serving app on port 8080...
Rebuilding...
Completed without errors on Fri Jun 17 2016 10:54:35 GMT+0100 (BST)
>> File truffle.js changed.
Rebuilding...
Completed without errors on Fri Jun 17 2016 11:05:23 GMT+0100 (BST)
```

The stylesheets don't seem to be effected by changing their destination path.

**Comment by zlatinov** [comment]
If you want Truffle to pack everything in app.js, you must have it defined with this exact name - "app.js".

http://truffle.readthedocs.io/en/latest/getting_started/build/

> Special note: If you want the default builder to bootstrap your application on the frontend, make sure you have a build target called app.js which the default builder can append code to. It will not bootstrap your application with any other filename.

**Comment by tcoulter** [comment]
Thanks for responding @zlatinov. I'm going to close this ticket for housekeeping purposes. If either of you run into any issues don't hesitate to open another, or ask for help on the Truffle gitter: http://gitter.im/consensys/truffle
