### ISSUE TITLE
Better error handling needed for invalid import

### ISSUE THREAD

**Issue by raineorshine** [ConsenSys/truffle#178]
```sol
import "DoesNotExist.sol"
```

Running `truffle compile` with a contract that has an import statement for a file that does not exist reports an obscure error message:

```sh
TypeError: Cannot read property 'source' of undefined
    at include_source_for (/Users/raine/.nvm/versions/node/v5.5.0/lib/node_modules/truffle/lib/contracts.js:90:77)
    at walk_down (/Users/raine/.nvm/versions/node/v5.5.0/lib/node_modules/truffle/lib/contracts.js:108:9)
```

I think an easy fix would be to check for the existence of `contract` here:
https://github.com/ConsenSys/truffle/blob/master/lib/contracts.js#L89

Thoughts? If this sounds like a good idea, I'm happy to submit a pull request.

**Comment by tcoulter** [comment]
I believe this is fixed with Truffle 2.0.x 

For the record, this was a *great* idea, but I hadn't acted on it previously. Thanks for all your feedback and hard work.

If you see this as a problem in 2.0, please reopen.
