### ISSUE TITLE
"Invalid params" when deploying to Parity from Truffle

### ISSUE THREAD

**Issue by harlantwood** [ConsenSys/truffle#179]
Deploying our contract to geth works fine.  But when we try to deploy to Parity we get:

```
$ truffle deploy -e testnet
Using environment testnet.
Checking sources...
Compiling DynamicToken.sol...
Collecting dependencies...
Error deploying DynamicToken:

Invalid params

Deploy failed. See above.
```

FWIW, this is [the contract](https://github.com/CoMakery/comakery-ethereum/blob/master/contracts/DynamicToken.sol) (and surrounding truffle environment).

Any ideas?

**Comment by harlantwood** [comment]
The parity team had good feedback in https://github.com/ethcore/parity/issues/1317 --

> Parity is a bit more strict (spec conformant) in terms of accepted parameters format. I bet it's gas or gasPrice being send as a number instead of hex values.

> Indeed - please provide the JSON of the RPC that fails and we'll probably be able to point out where you're being non-conformant with the Ethereum JSONRPC spec.

@tcoulter is there a way to print out json RPC arguments during deploy?  I tried `DEBUG=* truffle deploy` without success.

If not, can you point me to roughly where in the Truffle code to stick some debugging?  I poked around contract.js's deploy section but didn't see where we actually generate the JSON for the RPC ...

**Comment by thiagodelgado111** [comment]
@harlantwood can you try this? 
```
truffle deploy -e testnet --verbose-rpc
```

**Comment by harlantwood** [comment]
Thanks @thiagodelgado111!  Works like a charm; full output here: https://github.com/ethcore/parity/issues/1317#issuecomment-226980965

**Comment by harlantwood** [comment]
OK, @tomusdrw says

> Data should be prefixed with 0x

Hopefully if we made this change in Truffle, it would still work with geth (etc), and now with parity as well.

This does seem to be the expected format in the ETH JSON RPC docs: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction

**Comment by tcoulter** [comment]
Good bug guys. I'll try to get it fixed in the upcoming version.

**Comment by tomusdrw** [comment]
The spec says how to encode output data: https://github.com/ethereum/wiki/wiki/JSON-RPC#output-hex-values but doesn't specify input format anywhere. Examples show `DATA` prefixed with `0x` though.

**Comment by harlantwood** [comment]
Fixed in Truffle 2.x, thanks @tcoulter.

**Comment by ethers** [comment]
> The spec says how to encode output data: https://github.com/ethereum/wiki/wiki/JSON-RPC#output-hex-values but doesn't specify input format anywhere.

Would someone familiar mind tightening up the JSON-RPC spec?  maybe @tomusdrw ?

**Comment by tomusdrw** [comment]
It was already updated since then, I was also told that geth will become stricter in terms of accepted formats.
