### ISSUE TITLE
truffle compile should write abi and binary info

### ISSUE THREAD

**Issue by ckeenan** [ConsenSys/truffle#18]
Currently to write abi info you must do `truffle deploy` which is unnecessary for some applications

**Comment by flockonus** [comment]
Hey,
Got to this issue after googling `truffle export abi`, is there a command to get the contracts ABIs?
I just deployed with `truffle migrate --network rinkeby`, but don't find the contract ABIs

**Comment by maxme** [comment]
I was looking for this, but I didn't find it, so I wrote a simple tool that looks for `"abi": ...` in the build files and merge all of them to a single array:

https://github.com/maxme/truffle-export-abi
