### ISSUE TITLE
Data should be prefixed with 0x

### ISSUE THREAD

**Issue by harlantwood** [ConsenSys/truffle#180]
- when deploying contact
- perhaps other places as well?

This will fix deploying to Parity, which is more strict about confirming to the spec.

**Comment by harlantwood** [comment]
See also #179 & https://github.com/ethcore/parity/issues/1317

**Comment by harlantwood** [comment]
@thiagodelgado111

**Comment by thiagodelgado111** [comment]
Hi, @harlantwood! I put up a quick fix to add the 0x padding for contract’s creation but I couldn't test it because I can't make parity work properly here (my setup is fishy, I'm doing something wrong probably), and yes, I think it will be necessary for sending txs and calling functions too

**Comment by harlantwood** [comment]
Fixed in Truffle 2.x,.
