### ISSUE TITLE
Couldn't get any accounts! (from testrpc to geth)

### ISSUE THREAD

**Issue by BlockChange** [ConsenSys/truffle#187]
I'm trying to go from using the `testrpc` to using `geth` to test my project.

However, I have no idea where to start.

I'm running `geth` with: 

`geth --identity "MyNodeName" --genesis CustomGenesis.json --rpc --rpcport "8000" --rpccorsdomain "*" --datadir "~/blockchains/VPSChain" --port "30303" --nodiscover --ipcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpcapi "db,eth,net,web3" --autodag --networkid 1900 --nat "any" --dev console`

CustomGenesis.json:
```
{
    "nonce": "0x0000000000000042", 
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000", 
    "difficulty": "0x4000", 
    "alloc": {},
    "coinbase": "0x0000000000000000000000000000000000000000", 
    "timestamp": "0x00", 
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000", 
    "extraData": "Custem Ethereum Genesis Block", 
    "gasLimit": "0xffffffff"
}
```

I change the host in `truffle.js` and the port to `8000`. It seems to connect but says it has no accounts, which is pretty obvious, but how would I go about configuring `geth` to have some (test) accounts? And ones that are perhaps the same as the ones I use for `testrpc`?

How is this workflow imagined?

(Also when I try to deploy a `.sol` contract it gives `Error deploying Contracts: undefined`)

**Comment by tcoulter** [comment]
I'm not sure why you're getting `Error deploying Contracts: undefined`. However, the deployment code -- now called Migrations in Truffle 2.0 -- has been significantly revamped, so I'm going to close this issue.

As far as configuring geth with accounts, please see this wiki page: https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts

**Comment by moranthomas** [comment]
I got this error too and the reason was a variation of the others already highlighted.

So I had tried to upgrade the MetaMask Chrome plugin and it was in the process of doing that - So MetaMask was enabled but I had not logged in.

Removing MetaMask from Chrome did the trick (and later I re-installed the upgraded version)
