### ISSUE TITLE
truffle web3 version

### ISSUE THREAD

**Issue by ckeenan** [ConsenSys/truffle#19]
Right now a specific web3 is packaged w truffle. It would be cool if app.json could accept a pointer to a local web3 module

**Comment by tymat** [comment]
Bump

**Comment by ajunge** [comment]
Also with version 0.12.2 of web3 I got:  `Error: invalid address`. With version 0.10.0 works ok.

**Comment by tcoulter** [comment]
All, to use this, you need to specify a path to a web3 node module which includes both the frontend minified version as well as the node require'able version of web3.

e.g., your `app.json` would look something like this:

```
{
  // ...
  "rpc": {
    // Default RPC configuration.
    "host": "localhost",
    "port": 8545
  },
  "web3": "./node_modules/web3"
}
```

In this example, `./node_modules/web3` is relative to your project directory.
