### ISSUE TITLE
Receipt not found for transaction

### ISSUE THREAD

**Issue by BlockChange** [ConsenSys/truffle#190]
I keep getting `receipt not found for transaction` on a node initated with:

`geth --verbosity 6 --nodiscover --port 30303 --unlock "0x259af16d44f6897f98205af3b9d3382dbb0712d9" --rpc --rpcport 8101 --rpccorsdomain '*'  --rpcapi="db,eth,net,web3,personal" --mine console 2>> ~/gen.log`

After I deploy:

gen.log: (right after deploying 2 contracts)

    I0705 11:30:40.406084 eth/downloader/downloader.go:1942] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
    I0705 11:30:40.580404 core/tx_pool.go:303] (t) 3235396166313664 => [NEW_CONTRACT] (0x54d620) 49406d0ed84921e72c983d10113390437f8eceeb1ce7066b7440d4dd3387e83e
    I0705 11:30:40.580517 eth/api.go:1191] Tx(0x49406d0ed84921e72c983d10113390437f8eceeb1ce7066b7440d4dd3387e83e) created: 0xefbd415fc7cfafacd516d465705831fe7aa91b97
    I0705 11:30:40.580766 core/state/state_object.go:168] 259af16d44f6897f98205af3b9d3382dbb0712d9: #2 31336999999641396900000000000 (- 314159200000000000)
    I0705 11:30:40.580854 core/state/statedb.go:289] (+) efbd415fc7cfafacd516d465705831fe7aa91b97
    I0705 11:30:40.580884 core/state/state_object.go:168] 259af16d44f6897f98205af3b9d3382dbb0712d9: #3 31336999999641396900000000000 (- 0)
    I0705 11:30:40.580913 core/state/state_object.go:160] efbd415fc7cfafacd516d465705831fe7aa91b97: #0 0 (+ 0)
    I0705 11:30:40.580948 core/vm/vm.go:157] running byte VM c55cb748
    I0705 11:30:40.581088 core/vm/vm.go:160] byte VM c55cb748 done. time: 117.96µs instrc: 41
    I0705 11:30:40.581131 core/state/state_object.go:160] 259af16d44f6897f98205af3b9d3382dbb0712d9: #3 31336999999941133800000000000 (+ 299736900000000000)
    I0705 11:30:40.581164 eth/handler.go:776] broadcast tx to 0 peers
    I0705 11:30:40.581164 core/state/state_object.go:160] 259af16d44f6897f98205af3b9d3382dbb0712d9: #3 31336999999941133800000000000 (+ 0)
    I0705 11:30:40.581213 core/state/state_object.go:160] 0000000000000000000000000000000000000000: #0 58866200000000000 (+ 14422300000000000)
    I0705 11:30:40.581322 core/state_processor.go:108] receipt{med=e8e29d4bd59c8c90a68f43830fb135f89ec0965020e033aa36d0c17d983a5466 cgas=588662 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
    I0705 11:30:40.581147 core/tx_pool.go:303] (t) 3235396166313664 => [NEW_CONTRACT] (0x54d620) 5e4a6a8c0af12c5366c1617233881c40b344efcd80c5385dbe891aac88d29416
    I0705 11:30:40.581437 eth/api.go:1191] Tx(0x5e4a6a8c0af12c5366c1617233881c40b344efcd80c5385dbe891aac88d29416) created: 0xbf029f061b34b22d8a5b7b67cfc19086401a27bb
    I0705 11:30:40.581570 core/state/state_object.go:168] 259af16d44f6897f98205af3b9d3382dbb0712d9: #3 31336999999626974600000000000 (- 314159200000000000)
    I0705 11:30:40.581631 core/state/statedb.go:289] (+) bf029f061b34b22d8a5b7b67cfc19086401a27bb
    I0705 11:30:40.581653 core/state/state_object.go:168] 259af16d44f6897f98205af3b9d3382dbb0712d9: #4 31336999999626974600000000000 (- 0)
    I0705 11:30:40.581678 core/state/state_object.go:160] bf029f061b34b22d8a5b7b67cfc19086401a27bb: #0 0 (+ 0)
    I0705 11:30:40.581693 eth/handler.go:776] broadcast tx to 0 peers
    I0705 11:30:40.581718 core/vm/vm.go:157] running byte VM 2cb7b5c2
    I0705 11:30:40.582029 core/vm/vm.go:160] byte VM 2cb7b5c2 done. time: 282.615µs instrc: 148
    I0705 11:30:40.582081 core/state/state_object.go:160] 259af16d44f6897f98205af3b9d3382dbb0712d9: #4 31336999999911112200000000000 (+ 284137600000000000)
    I0705 11:30:40.582143 core/state/state_object.go:160] 259af16d44f6897f98205af3b9d3382dbb0712d9: #4 31336999999911112200000000000 (+ 0)
    I0705 11:30:40.582177 core/state/state_object.go:160] 0000000000000000000000000000000000000000: #0 88887800000000000 (+ 30021600000000000)
    I0705 11:30:40.582367 core/state_processor.go:108] receipt{med=22450a486e0682f5a6a2658ac0e4b14ba86fb973ea7f331c8f40619ebda9f320 cgas=888878 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
    I0705 11:30:41.085822 eth/api.go:1094] receipt not found for transaction 0x49406d0ed84921e72c983d10113390437f8eceeb1ce7066b7440d4dd3387e83e
    I0705 11:30:41.086068 eth/api.go:1094] receipt not found for transaction 0x5e4a6a8c0af12c5366c1617233881c40b344efcd80c5385dbe891aac88d29416
    I0705 11:30:41.587961 eth/api.go:1094] receipt not found for transaction 0x49406d0ed84921e72c983d10113390437f8eceeb1ce7066b7440d4dd3387e83e
    I0705 11:30:41.588005 eth/api.go:1094] receipt not found for transaction 0x5e4a6a8c0af12c5366c1617233881c40b344efcd80c5385dbe891aac88d29416
    I0705 11:30:42.090563 eth/api.go:1094] receipt not found for transaction 0x49406d0ed84921e72c983d10113390437f8eceeb1ce7066b7440d4dd3387e83e
    I0705 11:30:42.090566 eth/api.go:1094] receipt not found for transaction 0x5e4a6a8c0af12c5366c1617233881c40b344efcd80c5385dbe891aac88d29416

genesis.json:

    {
        "nonce": "0x0000000000000042",
        "timestamp": "0x0",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "extraData": "0x0",
        "gasLimit": "0x8000000",
        "difficulty": "0x400",
        "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "coinbase": "0x3333333333333333333333333333333333333333",
        "alloc": {
            "259af16d44f6897f98205af3b9d3382dbb0712d9": {
                "balance": "31337000000000000000000000000"
            }
         }
    }

Geth version: 1.4.9-stable

I'm using truffle/pudding to deploy.

It does seem to mention something about a `receipt` in the log, but I have no idea what is going wrong here.

(Note: I've seen this issue: http://ethereum.stackexchange.com/questions/2693/truffle-deploy-to-geth-failing-generating-receipt-not-found-repeatedly-from-g where the solution seemed to be **enabling mining, which is already enabled here**)

**Comment by harlantwood** [comment]
I'm getting the same issue.  Verbose RPC log:

```
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_getTransactionReceipt",
   >   "params": [
   >     "0x7f7c785e63e8cc8d81cce37adf8b80bf5f7402fe45c638a11be178c02a5ec461"
   >   ],
   >   "id": 2
   > }
 <   {
 <     "jsonrpc": "2.0",
 <     "id": 2,
 <     "result": null
 <   }
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_getTransactionReceipt",
   >   "params": [
   >     "0x7f7c785e63e8cc8d81cce37adf8b80bf5f7402fe45c638a11be178c02a5ec461"
   >   ],
   >   "id": 3
   > }
 <   {
 <     "jsonrpc": "2.0",
 <     "id": 3,
 <     "result": null
 <   }
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_getTransactionReceipt",
   >   "params": [
   >     "0x7f7c785e63e8cc8d81cce37adf8b80bf5f7402fe45c638a11be178c02a5ec461"
   >   ],
   >   "id": 4
   > }
 <   {
 <     "jsonrpc": "2.0",
 <     "id": 4,
 <     "result": null
 <   }
```

... this continues ad infinitum with `id` increasing each time.

**Comment by harlantwood** [comment]
FWIW, I removed the `--nodiscover` geth flag and now deploy works.

**Comment by BlockChange** [comment]
@harlantwood That's weird and unexpected behaviour.

I eventually got it to work by following this: http://tech.lab.carl.pro/kb/ethereum/testnet_setup

And I suspect because I made a new user for that, it was something in the homefolder, like `.ethash` that was not right.

**Comment by tcoulter** [comment]
Hmm. This appears to be a geth configuration issue and not necessarily a Truffle issue. I'm going to close this to keep the issues list clean. If you're still running into it please reopen and comment. Thanks!
