### ISSUE TITLE
Using environment-specific config.js for setting up account addresses

### ISSUE THREAD

**Issue by Ectsang** [ConsenSys/truffle#191]
Is there any way to have
```
module.exports = {
  rpc: {
    host: "localhost",
    port: 8899
  },
  _accounts: {
    buyer: '0x1111111...',
    seller: '0x222222...'
  }
}
```
And then access _accounts in app.js? The _accounts object would be different for development vs. test vs. staging vs. production.

**Comment by tcoulter** [comment]
This seems very specific to your dapp (i.e., "buyer" and "seller"). I recommend you have buyer and seller addresses within a contract on chain rather than within configuration. If you want the accounts available to you from your Ethereum client, you can always call `web3.eth.getAccounts()`.
