### ISSUE TITLE
Library not deployed or linked

### ISSUE THREAD

**Issue by raineorshine** [ConsenSys/truffle#192]
It took me a long time to debug this because the result of leaving out TestLib from truffle.js was that the contract compiled correctly, the tests ran, but **contract functions unexpectedly returned 0**. This only occurs when manually whisking contracts instead of using `.deployed()`.

**EDIT:** I have discovered that this is due to truffle not deploying or linking the library for some reason. The address field in the whisked `TestLib.sol.js` is empty.

I very narrow issue, but I am reporting it here since it is a very sneaky problem.

Full repo to reproduce: https://github.com/raineorshine/truffle-192

**Suggested change:** Display a useful error message when the user has omitted a library from the deploy section of their truffle.js (or automatically compile all libraries in the `contracts` folder).

MetaCoin.sol:

```js
import 'TestLib.sol';

contract MetaCoin {
  function MetaCoin() {
    TestLib.Foo(); // the issue only occurs when a library function is called
  }

  function GetAnswer() constant returns(uint) {
    return 42;
  }
}
```

TestLib.sol:

```js
library TestLib {
  struct Data {
    uint n;
  }

  function Foo() {
  }
}
```

truffle.js

```js
module.exports = {
  deploy: [
    "MetaCoin"
    // missing TestLib
  ],
  rpc: {
    host: "localhost",
    port: 8545
  }
};
```

test/metacoin.js

```js
const MetaCoinWhisked = require('../environments/test/contracts/MetaCoin.sol.js')
const Pudding = require('ether-pudding')

// load Web3, pudding, and contracts
Pudding.setWeb3(web3)
MetaCoinWhisked.load(Pudding)

contract('MetaCoin', function(accounts) {
  it('should return answer from .deployed() contract', function() {
    const meta = MetaCoin.deployed()
    return meta.GetAnswer()
      .then(data => assert.equal(data.toString(), '42'))
  })
})

describe('MetaCoinWhisked', function() {
  const accounts = web3.eth.accounts

  it('should return answer from whisked contract', function() {
    return MetaCoinWhisked.new({ from: accounts[0] })
      .then(meta => meta.GetAnswer())
      .then(data => assert.equal(data.toString(), '42'))
  })
})
```

**Comment by raineorshine** [comment]
Still major issues with this. I'm going to try moving to truffle v2, but I wish I knew what was causing the problem anyway.

My library is not getting deployed (address is blank in whisked file), even though TestLib is listed in the deploy section of truffle.js.

TestLib.sol.js:

```js
  var contract_data = {
    abi: [{"constant":false,"inputs":[],"name":"Foo","outputs":[],"type":"function"}],
    binary: "606060405260268060106000396000f3650301c67926cf50606060405260e060020a6000350463bfb4ebcf81146024575b6007565b00",
    unlinked_binary: "606060405260268060106000396000f3650301c67926cf50606060405260e060020a6000350463bfb4ebcf81146024575b6007565b00",
    address: "", // why is this empty?
    generated_with: "2.0.9",
    contract_name: "TestLib"
  };
```

**Comment by tcoulter** [comment]
@raineorshine I didn't see this comment you made:

> Full repo to reproduce: https://github.com/raineorshine/truffle-192

Awesome. This is exactly what I need in bug reports. Let me give it a shot.

**Comment by tcoulter** [comment]
Oh, I think I know this answer.

You're "whisking" yourself, which doesn't do any library linking. If you were to check out `MetaCoinWhisked`'s binary, it would include text like `__ConvertLib_________` in it. These are queues for the linker (i.e. Truffle) to replace that text with the actual address of the library. But since you're circumventing this process within Truffle, that text is not being replaced, effectively creating a corrupted binary. When you try to deploy a "corrupted binary" you won't get any error messages, just 0x, at least from geth. The TestRPC should complain though (and that's a bug in the TestRPC if it doesn't).

**Comment by tcoulter** [comment]
This is all just conjecture. I still need to try it.

**Comment by raineorshine** [comment]
That makes sense, and thanks for taking a look.

I got around the "no constructor arguments" limit of truffle v1 for a while, but eventually needed that functionality, hence whisking manually.

**Comment by raineorshine** [comment]
All working now. Here's my hacky workaround, fwiw:

```js
import 'babel-polyfill'
import requireFromString from 'require-from-string'
import { readFileSync } from 'fs'
import { join } from 'path'
import { merge, prop } from 'ramda'
import config from '../../config.js'
import truffleConfig from '../../truffle.js'
const Pudding = require('ether-pudding')

const contractPath = join(__dirname, '../../', config.paths.contracts)

/** Removes the 0x from the beginning of an address */
const stripAddress = addressRaw => addressRaw.slice(0,2) === '0x'
  ? addressRaw.slice(2)
  : address.Raw

/**
  Replaces all library placeholders in the given string with addresses provided by a name -> address mapping.
  (source: string, libraries: { name: Address }) => string
*/
export const linkSource = (source = '', libraries = {}) => {
  // match library placeholders and capture the identifier
  const regex = /__([^_]*)_*/g
  return source.replace(regex, (match, name) => {
    if(!(name in libraries)) {
      throw new Error(`Found library "${name}" in unlinked bytecode, but no address with that name was provided in libraries mapping.`)
    }
    const addressRaw = prop(name)(libraries)
    return stripAddress(addressRaw)
  })
}

/** Compiles all libraries specified in the libraries field of truffle.js. */
export const compileLibraries = async web3 => {

  Pudding.setWeb3(web3)

  // compile each library
  const libraryNames = truffleConfig.libraries || []
  const libraryInstances = await Promise.all(libraryNames.map(async libName => {
    const Lib = require(join(contractPath, `/${libName}.sol.js`))
    await Lib.load(Pudding)
    const lib = await Lib.new({ from: web3.eth.accounts[0] })
    return { name: libName, lib }
  }))

  // constructor an object mapping: name -> address
  return libraryInstances.reduce((prev, next) => {
    return merge(prev, {
      [next.name]: next.lib.address
    })
  }, {})
}

/** Inserts the given library addresses into the whisked contract code with the given name and returns a final, linked contract constructor. */
export const link = async (web3, name, libraries) => {
  Pudding.setWeb3(web3)
  const puddingContractSource = linkSource(readFileSync(join(contractPath, `/${name}.sol.js`), 'utf-8'), libraries)
  const Contract = requireFromString(puddingContractSource)
  await Contract.load(Pudding)
  return Contract
}
```

I use it like this:

```js
const libraries = await compileLibraries(web3)
const MyContract = await link(web3, 'MyContract', libraries)
```

**Comment by tcoulter** [comment]
Hey @raineorshine. Is this something you still need to do with Truffle's new migration system?

If you run `deployer.link()` within a migration, even if you don't deploy that contract specifically (say, you want n MetaCoin contracts instead of a singleton), it'll link the library for you and you'll be able to use it in your application without having to do that yourself.

Also -- and this might be helpful to you -- EtherPudding 3.1.2 now manages linked libraries for you.  You can call `MyContract.link()`, passing in the library name as the first parameter and the library address as the second parameter, and it will provider you a binary that you can use for deployment. You can even change the linked address later by calling `.link()` with the same library name, and Pudding will take care of what I'm calling "selective relinking" for you.

There's no documentation for this feature of Pudding yet, but here's how the latest Truffle uses it: https://github.com/ConsenSys/truffle/blob/master/lib/linker.js#L24

Now that I think about it, because of this new feature in EtherPudding, I'm going to close this ticket. There's now much less you have to do yourself, even if you *do* want to continue whisking things yourself. :) 

Cheers!

**Comment by raineorshine** [comment]
Okay, thanks. Yes, all those things sound good... I might have to stick
with what I've got for the time being because I'm entering the phase of the
project where we are closing in on the alpha release, so I have more
limited time for refactoring or doing major upgrades and the necessary
learning/troubleshooting that comes with it. Thanks for your response.

**Comment by LionByol** [comment]
> All working now. Here's my hacky workaround, fwiw:
> 
> ```js
> import 'babel-polyfill'
> import requireFromString from 'require-from-string'
> import { readFileSync } from 'fs'
> import { join } from 'path'
> import { merge, prop } from 'ramda'
> import config from '../../config.js'
> import truffleConfig from '../../truffle.js'
> const Pudding = require('ether-pudding')
> 
> const contractPath = join(__dirname, '../../', config.paths.contracts)
> 
> /** Removes the 0x from the beginning of an address */
> const stripAddress = addressRaw => addressRaw.slice(0,2) === '0x'
>   ? addressRaw.slice(2)
>   : address.Raw
> 
> /**
>   Replaces all library placeholders in the given string with addresses provided by a name -> address mapping.
>   (source: string, libraries: { name: Address }) => string
> */
> export const linkSource = (source = '', libraries = {}) => {
>   // match library placeholders and capture the identifier
>   const regex = /__([^_]*)_*/g
>   return source.replace(regex, (match, name) => {
>     if(!(name in libraries)) {
>       throw new Error(`Found library "${name}" in unlinked bytecode, but no address with that name was provided in libraries mapping.`)
>     }
>     const addressRaw = prop(name)(libraries)
>     return stripAddress(addressRaw)
>   })
> }
> 
> /** Compiles all libraries specified in the libraries field of truffle.js. */
> export const compileLibraries = async web3 => {
> 
>   Pudding.setWeb3(web3)
> 
>   // compile each library
>   const libraryNames = truffleConfig.libraries || []
>   const libraryInstances = await Promise.all(libraryNames.map(async libName => {
>     const Lib = require(join(contractPath, `/${libName}.sol.js`))
>     await Lib.load(Pudding)
>     const lib = await Lib.new({ from: web3.eth.accounts[0] })
>     return { name: libName, lib }
>   }))
> 
>   // constructor an object mapping: name -> address
>   return libraryInstances.reduce((prev, next) => {
>     return merge(prev, {
>       [next.name]: next.lib.address
>     })
>   }, {})
> }
> 
> /** Inserts the given library addresses into the whisked contract code with the given name and returns a final, linked contract constructor. */
> export const link = async (web3, name, libraries) => {
>   Pudding.setWeb3(web3)
>   const puddingContractSource = linkSource(readFileSync(join(contractPath, `/${name}.sol.js`), 'utf-8'), libraries)
>   const Contract = requireFromString(puddingContractSource)
>   await Contract.load(Pudding)
>   return Contract
> }
> ```
> 
> I use it like this:
> 
> ```js
> const libraries = await compileLibraries(web3)
> const MyContract = await link(web3, 'MyContract', libraries)
> ```

can we call the link() function directly?
