### ISSUE TITLE
Truffle's contract import code does not honor commented code

### ISSUE THREAD

**Issue by prashantpawar** [ConsenSys/truffle#194]
Follwing code:

```
import "hello.sol";
//import "world.sol";
```

will result in truffle trying to include world.sol even though that line is commented out.

**Comment by shayanb** [comment]
+1

**Comment by prashantpawar** [comment]
Just saw Solidity 2.0, haven't tried it yet, but I assume this issue should be solved now since now there is a proper parsing of Solidity files. Will report after trying 2.0

(Funny story, I have been writing Solidity parserr in PEG.js myself trying to solve this problem: https://github.com/prashantpawar/truffle/blob/feature/better_parsing_of_imports/lib/solidityparser.pegjs, good thing you guys beat me to it)

**Comment by tcoulter** [comment]
This issue looks resolved on 2.0! (i.e., works fine on my machine.) I'm doing some cleanup of the open issues here, so please reopen if it's still an issue. Thanks!
