### ISSUE TITLE
Commented snippet causes compile to fail

### ISSUE THREAD

**Issue by Schaeff** [ConsenSys/truffle#198]
`truffle compile` succeeds or fails with `SyntaxError: Expected "{", "}", any character, comment, end of line or whitespace but end of input found.` depending on whether a couple functions are commented out in my contract.

Might be related to #194

**Comment by tcoulter** [comment]
Have you tried this with Truffe 2.0?

**Comment by Schaeff** [comment]
This was actually in 2.0, never happened in 1.x. Toggling comment back and forth seems to fix the bug, which makes it sound like it's not deterministic. I'll try to reproduce.

**Comment by tcoulter** [comment]
@Schaeff This error message looks like it's coming from the solidity-parser, a Javascript parser for solidity that Truffle uses before sending code to the compiler. If you can find me exact code that causes compilation to fail, that'd be great. Thanks!

**Comment by tkeber** [comment]
This happens to me as well with Truffle v2.0.4, e.g. with this contract

```
contract Test {
    function testSol() returns(address addr) {
        // if (true) {
            addr = msg.sender;
        // }
        return addr;
    }
}
```

**Comment by chatch** [comment]
i'm seeing this also. replacing //  with a /*    */ comment works around it.

i tried running the solidity-parser directly on the contract but it appears to parse fine. so maybe truffle is changing something before feeding it to the parser?

**Comment by chatch** [comment]
ok actually it does happen calling solidity-parser directly if parsing 'imports' as per truffle/lib/profiler.js:137:

var imports = SolidityParser.parse(body, "imports");

I've created an issue here https://github.com/ConsenSys/solidity-parser/issues/7

**Comment by tcoulter** [comment]
Fixed on master. Will go out with the next release. Thanks everyone for the report!
