### ISSUE TITLE
Update deployed() to 2.0

### ISSUE THREAD

**Issue by ramvi** [ConsenSys/truffle#199]
Make all deployed contracts available through the API. Today the legacy code `[contract name].deployed()` gives you access to the deployed contract including its address. With the release of 2.0 and migrations it would make more sense for change deployed() or create a new function allDeployed() which returns an array of all the deployed contract. Preferably with the constructor param, so you can keep them apart.

```
> Token.allDeployed()
[
{"address": "0x123", "name": "Unicorn", "decimals":8 } // keys from contract constructor
]
```

Now it seems the the temporary solution is to write contract addresses to file and load them in your app

**Comment by tcoulter** [comment]
Hi there @ramvi. There's no way to know all deployed versions of a contract on a network. The goal for `deployed()` is to provide the address of one contract -- i.e., if your contract is a singleton, like a registry or a factory, this will provide you with an instance of the contract abstraction that points to the address of the deployed contract. If you'd like some sort of registry to manage all deployed contracts, I recommend you create a registry contract that you deploy to keep track of what's been deployed.

This is to say that with Truffle 2.0, the `deployed()` function hasn't changed, and it's goal has always been providing the means to interact with a single instance of the contract.
