### ISSUE TITLE
truffle test ignores config values from truffle.js (e.g. a gas value)

### ISSUE THREAD

**Issue by drvadson** [ConsenSys/truffle#202]
As a result, any big contract fails to deploy before tests are run.
Looks like the problem in this deploy() function:

https://github.com/ConsenSys/truffle/blob/master/lib/test.js#L90

The options object is created on the fly and the gas value is not there.

**Comment by tcoulter** [comment]
This should have been fixed in version 2.0.4. Could upgrade and let me know
if that fixes your issue?

**Comment by drvadson** [comment]
I'm running truffle 2.0.4. It was fixed for truffle migrate command, but not for truffle test. Here is how it works:

`$ truffle migrate --verbose-rpc
Compiling Registrar.sol...
Writing artifacts to ./build/contracts
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_accounts",
   >   "params": [],
   >   "id": 1
   > }
 <   {
 <     "jsonrpc": "2.0",
 <     "id": 1,
 <     "result": [
 <       "0xd4aa85f84dc132be2203c53b53e67f17ed06219e",
 <       "0x41e1603d32eedeb352c8c92e8f065832285535d4"
 <     ]
 <   }
Running migration: 1_initial_migration.js
  Deploying Migrations...
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_sendTransaction",
   >   "params": [
   >     {
   >       "from": "0xd4aa85f84dc132be2203c53b53e67f17ed06219e",
   **>       "gas": "0x1e8480",**
   >       "gasPrice": "0x174876e800",
   >       "data": "0x606060405260008054600160a060020a0319163317905560f7806100236000396000f3606060405260e060020a60003504630900f01081146038578063445df0ac1460b05780638da5cb5b1460b8578063fdacd5761460c9575b005b60366004356000805433600160a060020a039081169116141560ac576001547ffdacd5760000000000000000000000000000000000000000000000000000000060609081526064919091528291600160a060020a0383169163fdacd5769160849160248183876161da5a03f1156002575050505b5050565b60ed60015481565b60ed600054600160a060020a031681565b603660043560005433600160a060020a039081169116141560ea5760018190555b50565b6060908152602090f3"
   >     }
   >   ],
   >   "id": 1
   > }`

Note that "gas" and "gasPrice" are present in the sendTransaction call. Now with truffle test:

`$ truffle test test/registrar.js --verbose-rpc
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_accounts",
   >   "params": [],
   >   "id": 1
   > }
 <   {
 <     "jsonrpc": "2.0",
 <     "id": 1,
 <     "result": [
 <       "0xd4aa85f84dc132be2203c53b53e67f17ed06219e",
 <       "0x41e1603d32eedeb352c8c92e8f065832285535d4"
 <     ]
 <   }


  Contract: Registrar
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_accounts",
   >   "params": [],
   >   "id": 2
   > }
 <   {
 <     "jsonrpc": "2.0",
 <     "id": 2,
 <     "result": [
 <       "0xd4aa85f84dc132be2203c53b53e67f17ed06219e",
 <       "0x41e1603d32eedeb352c8c92e8f065832285535d4"
 <     ]
 <   }
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_sendTransaction",
   >   "params": [
   >     {
   >       "from": "0xd4aa85f84dc132be2203c53b53e67f17ed06219e",
   >       "data": "0x606060405260008054600160a060020a0319163317905560f7806100236000396000f3606060405260e060020a60003504630900f01081146038578063445df0ac1460b05780638da5cb5b1460b8578063fdacd5761460c9575b005b60366004356000805433600160a060020a039081169116141560ac576001547ffdacd5760000000000000000000000000000000000000000000000000000000060609081526064919091528291600160a060020a0383169163fdacd5769160849160248183876161da5a03f1156002575050505b5050565b60ed60015481565b60ed600054600160a060020a031681565b603660043560005433600160a060020a039081169116141560ea5760018190555b50565b6060908152602090f3"
   >     }
   >   ],
   >   "id": 1
   > }
`

Now sendTransaction has no gas values set, so contract does not get deployed:

`1) "before all" hook: prepare suite


  0 passing (9s)
  1 failing

  1) Contract: Registrar "before all" hook: prepare suite:
     Error: The contract code couldn't be stored, please check your gas amount.
      at Object.callback (/usr/local/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/contract.js:147:46)
      at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/method.js:142:25
      at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/requestmanager.js:89:9
      at /usr/local/lib/node_modules/truffle/lib/provider.js:27:9
      at request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:114:13)
      at dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
`

**Comment by tcoulter** [comment]
Hmm. Nothing in Truffle ever sets the gas limit to `0x1e8480`. Can you double check your application to ensure this isn't coming from your side?

**Comment by tcoulter** [comment]
Ah, nevermind. I misinterpreted. Let me look into it.

**Comment by tcoulter** [comment]
This has been fixed for a few weeks now. I'm going to close this ticket. Let me know if you are still having issues.
