### ISSUE TITLE
Readme is misleading

### ISSUE THREAD

**Issue by iurimatias** [ConsenSys/truffle#21]
In the readme, it says: "'Truffle shares many similarities to the Embark Framework but differs in philosophy. The main development goals of Truffle are:"

This seems to be imply erroneously that the development goals can't be done with Embark and difference lies there, misleading the reader. Could you please remove "but differs in philosophy".
Also please consider contributing.

**Comment by tcoulter** [comment]
Hi Iuri. I honestly believe the statement in the Readme to be correct and I don't consider it to be misleading. I do think Truffle intends to do things differently.

Regarding contributing, I think Truffle's functionality differs significantly from that of Embark and it might be too late to merge the two (though I could be wrong). That said, in multiple interactions with you it seems you've been less than happy that Truffle exists, and during those interactions you did not come off as friendly or genuinely interested in having a dialog about what makes Truffle and Embark different. I heavily pushed the idea within Consensys of merging the two codebases, but ultimately the tone of your interactions caused us not to consider the idea further. 

We might reconsider this in the future - in fact, I would like that. But right now we see ourselves as taking a different approach, and we're going to see that through. If you have any questions or would like to talk more, please let me know.

**Comment by iurimatias** [comment]
My main issue is really that I consider the Readme to be misleading to readers as I have explained before. I would really appreciate if you could fix it.
Time, I can't believe you can say that I didn't came across as "genuinely interested in a dialog", I invited you to discuss this several times on reddit and you didn't show any interest.

**Comment by tcoulter** [comment]
I felt I was accused of not caring about the community - which I believe is a statement you said explicitly. 

Still, will you be at DEVCON? I hope to be there (still unsure though) and it would be great to talk about this in person instead of over text.

**Comment by iurimatias** [comment]
|  which I believe is a statement you said explicitly

Where did I say that?

**Comment by tcoulter** [comment]
https://www.reddit.com/r/ethereum/comments/3cb8sq/truffle_development_environment_for_ethereum/

It started with "ripoff", then "Truth is, I'm too excited about the imminent ethereum release to care too much about this. :)" (basically, equivalent to "I don't care what you're doing") to "Embark is open to collaboration if ConsenSys likes the open source spirit." - at this point, given the other comments, it seemed you suggested we don't. This isn't just my personal opinion; I looked to others to help me understand your tone.

Regardless, this is all water under the bridge. Let's mend this at DEVCON.

**Comment by iurimatias** [comment]
note: So bear in mind that with text communications can be quite hard to interpret tone.. so please take this in a friendly way.

Forgive me the word 'ripoff', perhaps it's was too strong, it did felt to me at the time that ConsenSys wanted his own embark and was simply copycatting the whole functionality instead of contributing to an existing project. I think you can agree it was definitely 'inspired' at the very least given the many similarities. I also clarified at the time a lot of the misconceptions, but the readme never corrected this.

It seems that when you decided to create truffle (which is absolutely your right ofc) , and I'm assuming you acted in good faith here, it seems you had misunderstood what embark could do - leading to the creation of truffle - and I wished you had talked to me to clarify some features and instead contributed if needed like so many people do so there wouldn't be duplication of efforts like this.

P.S I see you fixed some of the Readme in the meanwhile, many thanks for this. Let me know if you ever visit Montreal.

**Comment by jmlubin** [comment]
Iuri, Tim,

Maybe we should get on a call this week or next and discuss the kinds of dApps and tools we are all building and how we might move forward either collaboratively. or perhaps helpfully in parallel?

Iuri, do you communicate much with Caktux?  Do you have partners on the project(s) you are working on?

Regards,
Joe



-- 


Joseph Lubin // Founder
joseph.lubin@consensys.net <mailto:andrew.keys@consensys.net> 
917.312.3550
240 Kent Ave Brooklyn NY 11249

**Comment by tcoulter** [comment]
Hi Joe. Would be happy to.

**Comment by iurimatias** [comment]
@jmlubin Happy to! :D I know Caktux yes

**Comment by jmlubin** [comment]
Great.  How’s this Friday at 3:00 PM EDT?

What’s a good email for you Iuri?



-- 


Joseph Lubin // Founder
joseph.lubin@consensys.net <mailto:andrew.keys@consensys.net> 
917.312.3550
240 Kent Ave Brooklyn NY 11249

**Comment by tcoulter** [comment]
Works great for me. Thanks Joe.

**Comment by iurimatias** [comment]
@jmlubin I'm too busy this week, next week is better. i'll try to contact you in some way.

**Comment by jmlubin** [comment]
Ok.  Please disregard the meeting invite.


-- 


Joseph Lubin // Founder
joseph.lubin@consensys.net <mailto:andrew.keys@consensys.net> 
917.312.3550
240 Kent Ave Brooklyn NY 11249
