### ISSUE TITLE
Why is truffle migrate used to commit contracts to the network? 

### ISSUE THREAD

**Issue by maraoz** [ConsenSys/truffle#212]
The name `migrate` is kind of misleading. Couldn't it be called `deploy` or `commit`?

**Comment by tcoulter** [comment]
It comes from a notion created in Rails: http://edgeguides.rubyonrails.org/active_record_migrations.html

The idea is you're migrating the state of your deployment over time. You won't deploy your contracts just once. If you continue developing your dapp, you'll fix bugs, add features, etc. and will need to *migrate* your app state as time goes on.
