### ISSUE TITLE
Truffle build is broken. Truffle deploy doesnt work

### ISSUE THREAD

**Issue by syedshahzebhasnain** [ConsenSys/truffle#213]
Hi!

I just upgraded my truffle however now i am not able to build and deploy the project ( it was working fine previously). i reinstalled all major components of NPM packages required by truffle.

To test this issue, i did a truffle init first. It seems to be broken there. However i did get a work around for it. 

"Error: ENOENT: no such file or directory, lstat 'D:\truffletest\build\contracts'
    at Error (native)"
_This issue was resolved by creating a contracts folder on the given path._

Now when i run **truffle build**, it gives me this error
---------------------------------------------------------------------------------------------------------------
Truffle v2.0.4 - a development framework for Ethereum

Usage: truffle [command] [options]

Commands:

  build           => Build development version of app
  compile         => Compile contracts
  console         => Run a console with deployed contracts instantiated and available (REPL)
  create:contract => Create a basic contract
  create:test     => Create a basic test
  exec            => Execute a JS file within truffle environment
  init            => Initialize new Ethereum project, including example contracts and tests
  list            => List all available tasks
  migrate         => Run migrations
  networks        => Show addresses for deployed contracts on each network
  serve           => Serve app on localhost and rebuild changes as needed
  test            => Run tests
  version         => Show version number and exit
  watch           => Watch filesystem for changes and rebuild the project automatically

Any help guys???
--------------------------------------------------------------------------------------------------------------

**Comment by tcoulter** [comment]
`truffle migrate` has replaced the `truffle deploy` command to allow for more complex deployments. You now need to write "migrations", which are deployment scripts. You should do this before running `truffle build`. Please see the documentation here: http://truffle.readthedocs.io/en/latest/getting_started/migrations/
