### ISSUE TITLE
build need a running rpc

### ISSUE THREAD

**Issue by ajunge** [ConsenSys/truffle#217]
in truffle 2.0.4 if I do a `ŧruffle build` it needs to do a `eth_accounts` on the rpc server? I just want lo build (in my case only run webpack). On 1.0.3 this was not needed, so I can run webpack without the need for an rpc server

**Comment by tcoulter** [comment]
Thanks @ajunge! This has already been fixed and pushed out in v2.0.7. Thanks for the report!
