### ISSUE TITLE
Truffle serve doesnt seem to pick up the correct path

### ISSUE THREAD

**Issue by syedshahzebhasnain** [ConsenSys/truffle#218]
**Hi !

I have been trying to do a truffle serve and i am yet to over come this issue**

D:\truffletest>truffle build
-> Works perfectly
D:\truffletest>truffle migrate
-> Works perfectly

D:\truffletest>truff serve
Serving app on port 8080...
Rebuilding...
Completed with errors on Wed Aug 03 2016 01:29:49 GMT+0500
Error: Cannot find module 'D:   ruffletesuildcontractsMetaCoin.sol.js' from 'C:\Users\shahzeb\AppData\Local\Temp'
    at C:\Users\shahzeb\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\shahzeb\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\shahzeb\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\shahzeb\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\shahzeb\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\shahzeb\AppData\Roaming\npm\node_modules\truffle\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

**I can see that "Error: Cannot find module 'D:   ruffletesuildcontractsMetaCoin.sol.js' " is not picking the correct path.

The path should be D:\truffletest\build\contracts\MetaCoin.sol.js**

Any way to fix this?

**Comment by LaurentMT** [comment]
Same problem here with truffle 2.0.4 on a windows machine.

**Comment by JefStat** [comment]
Same issue I run truffle from `git bash` and also tried `powershell` but I've seen `truffle serve` work after previously not working. As of right now truffle build fails with the same error as truffle serve

**Comment by gauravagarwal07** [comment]
does anybody found solution of this issue ?

**Comment by tcoulter** [comment]
No solution as of yet. We're still looking into this one. It's particularly hard to debug as the error message doesn't seem to be showing any of our code.

**Comment by gauravagarwal07** [comment]
@tcoulter checkout this thread : https://github.com/ConsenSys/truffle/issues/232

@ronazulay has suggested a solution for the problem and this fix is working for me .

**Comment by tcoulter** [comment]
FYI all: This has been fixed on master and will go out with the next Truffle release. Closing! Thanks!
