### ISSUE TITLE
truffle init in /var/www/html (apache, Ubuntu 14.04)

### ISSUE THREAD

**Issue by arkoe** [ConsenSys/truffle#220]
I am trying to init truffle within the html folder on my server, so I can see the /app/index.html live for testing purposes. However, when I run `truffle init` it does nothing, and then throws the message: `Aborted (core dumped)`.

When I tried it somewhere else:

```
cd ~
mkdir truffle-test
cd truffle-test
truffle init
```

It does work and creates the folders and files as it should. What could be the issue?

**Comment by arkoe** [comment]
A few minutes later I tried it again and it worked. However, when I run `truffle serve` it does kinda the same, first it starts, then aborts:

```
root@ubuntu-testvps:/var/www/html# truffle serve
Serving app on port 8080...
Aborted (core dumped)
```

**Comment by tcoulter** [comment]
Unfortunately this isn't something we can solve on our end. Whenever there's a core dump, in means something within node seriously went wrong; this is one of those things that "it's never supposed to do that". I'd look into your node installation and update or reinstall the latest nodejs.
