### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat

### ISSUE THREAD

**Issue by shayanb** [ConsenSys/truffle#221]
Just updated from truffle 1 to recent truffle 2 on Mac. and I get this error even on the samples (files made from `truffle init`).

```
🍺  truffle build
Error: ENOENT: no such file or directory, lstat '/XXX/smart_contracts/tmp/build/contracts'
    at Error (native)
```

**Comment by tcoulter** [comment]
Hi @shayanb, thanks for the report. This should have been fixed in this commit! Thanks! https://github.com/ConsenSys/truffle/commit/6bd17b1382ac25142445d1a0d52d8ad895c468ae
