### ISSUE TITLE
npm still points to 0.0.13

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/truffle#23]
Needs a version bump to new Truffle. :)

**Comment by tcoulter** [comment]
Yep. This will happen once I'm happy with 0.0.14. :) Total rewrite of the code (well, conversion from Coffee to ES6) so I wanted to put it through its paces.

**Comment by simondlr** [comment]
:+1:

**Comment by tcoulter** [comment]
Done. Published 0.0.14 to npm.
