### ISSUE TITLE
ReferenceError: network_id is not defined

### ISSUE THREAD

**Issue by mpolci** [ConsenSys/truffle#233]
When I give a wrong network name I get this error for an undefined `network_id` variable in the code:

```
$ truffle migrate --network wrong_name
/usr/lib/node_modules/truffle/lib/config.js:109
    throw new ConfigurationError("Cannot find network '" + network_id + "'");
                                                           ^

ReferenceError: network_id is not defined
    at Config.getRPCConfig (/usr/lib/node_modules/truffle/lib/config.js:109:60)
    at Config.props.provider (/usr/lib/node_modules/truffle/lib/config.js:83:26)
    at Config.Object.defineProperty.get [as provider] (/usr/lib/node_modules/truffle/lib/config.js:97:35)
    at /usr/lib/node_modules/truffle/node_modules/ether-pudding/index.js:206:18
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

```

**Comment by eduardonunesp** [comment]
Maybe it's because you haven't specificated that network id in your `truffle.js` file, take a look at http://truffle.readthedocs.io/en/latest/advanced/configuration/#networks for more information.

**Comment by tcoulter** [comment]
This has been fixed in Truffle 3.0. The new error message looks like this:

```
Tims-MacBook-Pro:test3 tim$ ../truffle/cli.js migrate --network notconfigured
Unknown network "notconfigured". See your Truffle configuration file for available networks.
```

Thanks!

**Comment by cmycaro** [comment]
I also got the same error~ the undefined thing is the contract 
`Caros-MacBook-Pro:~ caro$ truffle migrate
Running migration: 2_deploy_contracts.js

/Users/caro/migrations/2_deploy_contracts.js:5
   deployer.deploy(MyAdvancedToken);
                   ^
ReferenceError: MyAdvancedToken is not defined
    at module.exports (/Users/caro/migrations/2_deploy_contracts.js:5:20)
    at /usr/local/lib/node_modules/truffle/lib/migrate.js:109:7
    at /usr/local/lib/node_modules/truffle/lib/require.js:82:7
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)`

**Comment by tcoulter** [comment]
@cmycaro Your error is very different. My assumption is you recently upgraded from Truffle 2.0 to 3.0. please see the upgrade guide here to show you how to properly pull in contract artifacts into your migrations: http://truffleframework.com/tutorials/upgrading-from-truffle-2-to-3

If you're still having trouble, please join the Truffle Gitter chat channel and ask your question there. Thanks!

**Comment by cmycaro** [comment]
Dear Tim Coulter，


Thanks for your answer. I will have a try to know what’s going on！


Original Message
Sender:Tim Coulternotifications@github.com
Recipient:ConsenSys/truffletruffle@noreply.github.com
Cc:cmycaro724517447@qq.com; Mentionmention@noreply.github.com
Date:Friday, Feb 24, 2017 21:26
Subject:Re: [ConsenSys/truffle] ReferenceError: network_id is not defined(#233)


@cmycaro Your error is very different. My assumption is you recently upgraded from Truffle 2.0 to 3.0. please see the upgrade guide here to show you how to properly pull in contract artifacts into your migrations: http://truffleframework.com/tutorials/upgrading-from-truffle-2-to-3
If you're still having trouble, please join the Truffle Gitter chat channel and ask your question there. Thanks!
