### ISSUE TITLE
Don't check for existence of web3 until window.onload()

### ISSUE THREAD

**Issue by tcoulter** [ConsenSys/truffle#236]
@kumavis says there are race conditions with Metamask (and presumably mist) otherwise.

**Comment by kumavis** [comment]
we are now reccomending awaiting page load event
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#web3---ethereum-browser-environment-check

**Comment by neerajsaran** [comment]
@kumavis @flyswatter it looks like when i started the basic php server and hosted the file from there then it started working, i.e. I see MM account and MM asks for password but without php server running it does not work.
<img width="1162" alt="screen shot 2016-08-17 at 7 14 26 am" src="https://cloud.githubusercontent.com/assets/19916332/17734680/a996d002-644b-11e6-963e-e5639e92bae1.png">

**Comment by kumavis** [comment]
Yes, `file://` protocol does not work. Will add a note to the `faq/developers.md`

**Comment by kumavis** [comment]
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#https---web-server-required

**Comment by flyswatter** [comment]
Cool, looks like we could close this issue then?

**Comment by kumavis** [comment]
@flyswatter no, @tcoulter still needs to implement this ( or remove the build sys )
