### ISSUE TITLE
`truffle exec` broken in 2.0.7

### ISSUE THREAD

**Issue by tcoulter** [ConsenSys/truffle#245]
From Gitter via @maxweng:

@tcoulter I’ve updated to v2.0.7. Then, when I ran truffle exec, it just crashed saying TypeError: Cannot read property 'from' of undefined at /usr/local/lib/node_modules/truffle/lib/contracts.js:57:46.
I had traced into it. And I found that it’s something to do with your latest update on Contract.js.
It seems that in Contracts.provision, you updated the
var defaults = {
            from: options.from || options.rpc.from,
            gas: options.gas || options.rpc.gas,
            gasPrice: options.gasPrice || options.rpc.gasPrice
};

Max Weng @maxweng Aug 10 21:13
But at # 100 line in require.js, where you call Contracts.provision(), you seem to construct a new Option object to pass in, instead of passing the entire options.
I think that’s the cause of the crash. I just changed it to pass in the options variable. And it seems to be working now.

**Comment by rolandkofler** [comment]
Any chance that this will be in npm soon?

**Comment by tcoulter** [comment]
It already is! v2.0.8. :)
