### ISSUE TITLE
ENVIRONMENT VARIABLES NOT BEING SET?? WTF

### ISSUE THREAD

**Issue by emum8** [ConsenSys/truffle#248]
AFTER INSTALLING TRUFFLE I GET THE FOLLOWING ERROR:

'truffle' is not recognized as an internal or external command,
operable program or batch file.

ON WINDOWS 7.
HOW DO I ADD THE VARIABLES MANUALLY.
ALSO ETHEREUM SYNC IS SLOW AS SHIT AND TESTRPC FAILS TO INSTALL. FML!!!!

**Comment by tcoulter** [comment]
Hi there. I'm sorry you had an issue. That said, the best way to get support on this forum is to not use all caps. For all future reports, please write out the issue more clearly.

That said, the issue you're having is not an issue with Truffle, but rather npm. Make sure you have the latest node js installed (you can get it here: https://nodejs.org/en/ , download 6.x). Then reinstall truffle using `npm install -g truffle`. If you're still having trouble, post the node and npm version here, using the following commands:

```
$ node -v
$ npm -v
```

If these are the latest versions and are installed correctly, you shouldn't have to add items to the path yourself. npm should do it for you.

Regarding the TestRPC, make sure you follow the Windows Install Instructions, here: https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows

Now, I've never tried to install any of this on Windows 7. I've only tested 8.1 and 10. Please google the errors you receive and specifically look for solutions for Windows 7. Again, this is not a Truffle issue, but an issue with your installation of node and npm.

**Comment by emum8** [comment]
OK I've updated my NODE  to v6.4.0 and NPM 3.10.3. shit still don't work.
It installed truffle before but I couldn't use the CLI. after updating NODE and NPM i'm getting those new BUILD ERRORS.

Shit just doesn't work these days, 70% of shit I install with npm doesn't work.
