### ISSUE TITLE
migrate stalls when Parity SecureTransaction Signer is on

### ISSUE THREAD

**Issue by chatch** [ConsenSys/truffle#250]
When I run "truffle migrate" with Parity (morden) the migration hangs and never recovers. This is with the [Secure Transaction Signer](https://github.com/ethcore/parity/wiki/Secure-Transaction-Signer) turned on (Parity default). I can usually approve 1 or 2 of the transactions before it hangs.

This happens with the "truffle init" MetaCoin example too.

If using --unlock with Parity then there is no manual transaction signing and the migration works ok.

**Comment by chatch** [comment]
I just tried this again with the MetaCoin example and this time I got to the final contract which deployed (looking at the etherscan.io tx i could see) however migrate exited with "wasn't processed in 240 seconds!".  

truffle migrate output is here: 

Running migration: 1_initial_migration.js
  Deploying Migrations...
  Migrations: 0x5f18cd26e3f76576f127244cd009eff86793b596
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying ConvertLib...
  ConvertLib: 0xf165a84782395c6a666d7a4426f6d02920cbdd5c
  Linking ConvertLib to MetaCoin
  Deploying MetaCoin...
  MetaCoin: 0xb1547483c16ee5fd498cdafc77162fd5dda51dd3
Saving successful migration to network...

Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Transaction 0x0000000000000000000000000000000000000000000000000000000000000000 wasn't processed in 240 seconds!
    at Object.callback (/tmp/testmig/build/contracts/Migrations.sol.js:113:33)
    at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/method.js:142:25
    at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/requestmanager.js:89:9
    at request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
 

I'll try this again and see if I can figure out what's happening.

**Comment by tcoulter** [comment]
Interesting. I haven't used Parity. But the error:

```
0x0000000000000000000000000000000000000000000000000000000000000000 wasn't processed in 240 seconds!
```

... means that Parity returned a transaction id of 0x0000000000000000000000000000000000000000000000000000000000000000, which is obviously incorrect. To verify, can you run your migrations with the `--verbose-rpc` flag, and paste the output in a gist? That would give us more information about the values Parity is returning.

**Comment by chatch** [comment]
Good to know --verbose-rpc. Nice.  So Parity is indeed returning 0x0000000000000000000000000000000000000000000000000000000000000000
 See attached [truffle_migrate_verbose_rpc.txt](https://github.com/ConsenSys/truffle/files/438446/truffle_migrate_verbose_rpc.txt)

I'll try sending some tx's directly to Parity and see if I can replicate it.

**Comment by chatch** [comment]
possibly Parity is rejecting the transaction somewhere even though it appears to be accepted in Parity UI .. not sure. anyway it's not a truffle issue so closing..
