### ISSUE TITLE
truffle compile fails on solidity-stringutils

### ISSUE THREAD

**Issue by mike80439** [ConsenSys/truffle#251]
Compiling strings.sol (https://github.com/Arachnid/solidity-stringutils) results in:

[x] $ truffle compile
Compiling Test2.sol...
Compiling strings.sol...

/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filen
6236544

The "truffle migration" does not complete.

**Comment by tcoulter** [comment]
Well this is an odd error (and error message). Reproduced, thanks!

**Comment by tcoulter** [comment]
I've confirmed that this is a bug with the solc compiler and not with Truffle. I've written up an [example project that exposes the error](https://github.com/tcoulter/solc-result-bug) as well as submitted a [bug report](https://github.com/ethereum/solc-js/issues/44) to solc.js. Will leave this ticket open until the upstream issue is resolved, after which we'll upgrade our solc version.

**Comment by mike80439** [comment]
Thank you, Tim.

**Comment by tcoulter** [comment]
This appears to be fixed upstream. Please reopen if you have any issues. Cheers!
