### ISSUE TITLE
No Deploy Command

### ISSUE THREAD

**Issue by sparcusa** [ConsenSys/truffle#256]
truffle V2.0.8
Ubuntu 16.04

I installed truffle.   It runs.  But there is no deploy command.   Has deploy been deprecated?

Truffle v2.0.8 - a development framework for Ethereum

Usage: truffle [command] [options]

Commands:

  build            => Build development version of app
  compile          => Compile contracts
  console          => Run a console with deployed contracts instantiated and available (REPL)
  create:contract  => Create a basic contract
  create:migration => Create a new migration marked with the current timestamp
  create:test      => Create a basic test
  exec             => Execute a JS file within truffle environment
  init             => Initialize new Ethereum project, including example contracts and tests
  list             => List all available tasks
  migrate          => Run migrations
  networks         => Show addresses for deployed contracts on each network
  serve            => Serve app on localhost and rebuild changes as needed
  test             => Run tests
  version          => Show version number and exit
  watch            => Watch filesystem for changes and rebuild the project automatically

**Comment by tcoulter** [comment]
Truffle 2.0 had a significant feature upgrade, and one of those features was removing the very basic `deploy` feature in favor of migrations. Migrations are deployment scripts that you manage that allow for custom, complex deployments. Please read up on migrations, as that's what you'll use to deploy your contracts. http://truffle.readthedocs.io/en/latest/getting_started/migrations/
