### ISSUE TITLE
Compile fails when using pragma

### ISSUE THREAD

**Issue by chevdor** [ConsenSys/truffle#264]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

If the contract contains the keyword pragma, compiling fails with:
```
/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/index.js:39
      throw e;
      ^
SyntaxError: Expected "contract", "import", "library", comment, end of input, end of line or whitespace but "p" found. Line: 1, Column: 1
    at peg$buildException (/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/build/imports_parser.js:423:14)
    at Object.peg$parse [as parse] (/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/build/imports_parser.js:3355:13)
    at Object.parse (/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/index.js:34:23)
    at /usr/local/lib/node_modules/truffle/lib/profiler.js:134:36
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```
## Steps to Reproduce

Use a contract that starts with `pragma solidity 0.4.2;`

## Expected Behavior

it compiles

## Actual Results
it does not compile and throw an error

## Environment

* Operating System: OSX
* Truffle version:v2.0.8
* Ethereum client: n/a
* node version: v6.6.0
* npm version: 3.10.7

**Comment by baklinger** [comment]
I had the same issue. My config was:

- Operating System: OSX
- Truffle version:v2.0.7
- node version: v6.7.0
- npm version: 3.10.9

I've upgraded Truffle to version 2.1.0 and the issue seems to be solved. I can compile smart contracts with `pragma` without the SyntaxError exception.

**Comment by chevdor** [comment]
Ouch sorry for keeping this one open, I totally forgot it.
Indeed, in the previous version, the solidity parser could not take such fantasy :)

As you mention @baklinger, the new truffle version is the solution. Thanks for your input.

**Comment by skrajath** [comment]
I get the same issue 

- npm: '3.10.8'

- Truffle v2.1.1

- node version : v6.9.1

Is this related to something wrong in the written contract.
