### ISSUE TITLE
Truffle throw error when compiling correctly written sol.  

### ISSUE THREAD

**Issue by zalesky** [ConsenSys/truffle#285]
error when:
modifier onlyBefore(uint _time) { if (now >= _time) throw; _ ;}

working variant:
modifier onlyBefore(uint _time) { if (now >= _time) throw; _ }

must to be: http://solidity.readthedocs.io/en/develop/common-patterns.html?highlight=modifiers#restricting-access

**Comment by simondlr** [comment]
This is because Truffle still uses < 0.4.0 of solc.

**Comment by tcoulter** [comment]
Thanks Simon. I will be bumping solc today.

**Comment by mpolci** [comment]
@tcoulter I tested the new release 2.1.0, now the error is inverted.
Even if the `#pragma` statement is not specified `_;` works and `_` without the 
semicolon raises an error

**Comment by tcoulter** [comment]
Which error? I'm assuming that's an error coming from `solc`, in which case you'll have to go to them. I don't think the newest solc supports backwards compatibility based on the pragma statement.

**Comment by mpolci** [comment]
@tcoulter you are right, the error is `Error: Expected token Semicolon got 'RBrace'` and it comes from solc. I got the same error manually compiling the contract using `solc`.

**Comment by tcoulter** [comment]
I'm going to close this issue. If you're still running into trouble please open a new one.
