### ISSUE TITLE
npm install fails on Windows 7

### ISSUE THREAD

**Issue by haiqu** [ConsenSys/truffle#286]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

Yes. Seems unmanned.

## Issue

Cannot install truffle under Windows 7. The problem seems to be path lengths, which exceed the allowable length in that OS.

## Steps to Reproduce

npm install -g truffle

## Expected Behavior

I expect it to install. :)

## Actual Results

Partial screen dump:

C:\Users\Rob\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\ethereumjs-testrpc\node_modules\ethereumjs-wallet\node_modules\scrypt.js\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\Rob\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\ethereumjs-testrpc\node_modules\ethereumjs-wallet\node_modules\scrypt.js\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to file "Release\obj\copied_files\copied_files.tlog\copied_files.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\Users\Rob\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\ethereumjs-testrpc\node_modules\ethereumjs-wallet\node_modules\scrypt.js\node_modules\scrypt\build\copied_files.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to file "Release\obj\scrypt_wrapper\scrypt_wrapper.tlog\scrypt_wrapper.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\Users\Rob\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\ethereumjs-testrpc\node_modules\ethereumjs-wallet\node_modules\scrypt.js\node_modules\scrypt\build\scrypt_wrapper.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rob\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\ethereumjs-testrpc\node_modules\ethereumjs-wallet\node_modules\scrypt.js\node_modules\scrypt
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

## Environment

* Operating System:  Windows 7
* Truffle version: Repository lates I assume
* Ethereum client: Relevance?
* node version: 4.6.0
* npm version: 2.15.9

**Comment by haiqu** [comment]
Managed to compile tonight after updating to node 6.7.0

Closing ticket.

**Comment by tcoulter** [comment]
Hi Rob,

Regarding the Truffle Gitter:

> Yes. Seems unmanned.

There are 420 subscribed Gitter users at the time of this writing. There
are definitely users willing to help. I assume you caught people at the
wrong time.

That said, there is no paid support person, so please continue reaching out
to the community if you don't immediately get a response.

Cheers.

**Comment by haiqu** [comment]
It's OK, I've been in the open source community for years, I know how it works. Just glad to have found that the problem was on my end, I've given up on many projects due to complete lack of support.

Not that commercial software is any better. :)
