### ISSUE TITLE
Data returns 0x0000... in contracts that use libraries that are created with `.new`

### ISSUE THREAD

**Issue by raineorshine** [ConsenSys/truffle#298]
Is there anything special to know about using `MyContract.new(...)` for contracts that use libraries? I'm having an issue where the deployed contract is working but a manual `new` does not properly link (specifically, data stored via the library, such as with the `using ... for` syntax, is coming back as `0x0000...`).

This works:

```
// getData is a getter that retrieves data stored via a library
truffle(default)> MyContract.deployed().getData() // prints correct data
```

This returns `0x0000...` for all values stored using the library:
```
// this should print the exact same data (different contract instance, but initialized the same way and same getter)
truffle(default)> MyContract.new().then(contract => contract.getData().then(console.log)) // prints 0x0000...
```

Unless I am missing something, this seems to be a bug. I can provide more details but I wanted to check first if I was missing something obvious.

## Issue

Undeployed contracts are not linked properly.

## Steps to Reproduce

1. Deploy a contract that uses a library to store data
2. Call a getter to see that data returns `0x0000...`

(I can provide more details if necessary)

## Expected Behavior

Expect data to be stored and retrieved successfully.

## Actual Results

Data stored with library returns `0x0000...` Data stored using the main contract without any library functions works fine.

## Environment

* Operating System: OSX El Capitan
* Truffle version: 3.0.0-2
* Ethereum client: TestRPC 3.0.0
* node version: 6.1.0
* npm version: 3.8.6

**Comment by tcoulter** [comment]
Hey @raineorshine, my gut reaction is that you need to call `deployer.link()` or `deployer.autolink()` in your migrations. Truffle won't link these for you automatically *unless* you deploy a contract through `deployer.deploy()`. In order to ensure the correct linkage, you have to write that into your migration.

Say I have `MyContract` which relies on `MyLibrary`, and say I plan to have users create an instance of `MyContract` as they use my dapp (rather than deploy `MyContract` as a singleton). The initial migration, then, would look something like this:

`1_initial_migration.js`
```javascript
module.exports = function(deployer) {
  deployer.deploy(Migrations);
  deployer.link(MyLibrary, MyContract); 
};
```

That last line will edit the build artifacts to ensure `MyContract` is linked to `MyLibrary` properly.

**Comment by raineorshine** [comment]
Thank you, I am trying that out right now!

I am getting confused though as it does not seem to be happening anymore, and now I am getting `Invalid JSON RPC response: undefined`. It occurs with `MyContract.new(...)`. Other methods like `web3.eth.accounts` and `MyContract.at(...)` work fine. It appears that the contract is deployed successfully in testrpc. 

Any ideas?

**Comment by tcoulter** [comment]
Very interesting. `undefined` suggests a fairly big, uncaught issue. How are you using the TestRPC? Is it as a server or a library?

**Comment by raineorshine** [comment]
server

**Comment by raineorshine** [comment]
Possibly related to https://github.com/ConsenSys/ether-pudding/issues/39?

**Comment by raineorshine** [comment]
The `intermediary` function in MyContract.sol.js is called once with no error and no address set, and then it crashes somewhere inside web3.

**Comment by raineorshine** [comment]
Is there some kind of compatibility issue with web3 v0.17.0-beta?

**Comment by tcoulter** [comment]
There could be. I haven't tried that version yet, so it sounds plausible.

**Comment by raineorshine** [comment]
Downgraded to v0.16.0. Works now.

Sorry this issue wandered from its original stated problem.

How should we proceed with documenting/identifying the `0.17.0-beta` incompatibility? If it's a web3 bug, just skipping `0.17.0-beta` might be smart.

**Comment by tcoulter** [comment]
I think it's because Truffle/EtherPudding uses `0.16.x`. Is it automatically updating to the `-beta` version, or did you do that intentionally? 

No problem, by the way. This is good information to know.

**Comment by raineorshine** [comment]
npm will not install `0.17.0-beta` automatically if the specified version range is `^0.16.0`, since the `-beta` is there.

truffle#beta specifies web3 `^0.16.0`.
truffle#beta specifies ether-pudding `^3.2.0`.
ether-pudding#0.16.0 specifies web3 `^0.15.3`.

That's all fine. I think the problem is that I am explicitly using web3 `0.17.0-beta` in my project. I guess there is a peer dependency to use the same version of web3 that is used by truffle.
