### ISSUE TITLE
Promise.promisify not included

### ISSUE THREAD

**Issue by christianlundkvist** [ConsenSys/truffle#30]
If I write something like
```
var myBalance = Promise.promisify(web3.eth.getBalance)
```
I'm getting an error message
```
Fatal error: undefined is not a function
```

**Comment by tcoulter** [comment]
@christianlundkvist This should be fixed for tests on the `master` branch. If you get a chance to test it out that'd be great.

**Comment by tcoulter** [comment]
Closing this. Should be fixed within the next release (coming today)

**Comment by christianlundkvist** [comment]
Sorry, missed this thread! I need to clean up my github notification settings! The failure for me was in a mocha test. I'll try the new tests to see if it works. Thanks so much for fixing! :smile:
