### ISSUE TITLE
Generated getter for mapping from address => uint256[] generating incorrect ABI

### ISSUE THREAD

**Issue by dob** [ConsenSys/truffle#302]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

In my contract I have:
   
    mapping (address => uint256[]) public idsForContract;

The ABI in the truffle generated app.js file Contracts.all_networks object lists the output as

    "name": "idsForContract",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],

Note that the output is of type `uint256` instead of `uint256[]` which means that when I invoked the getter through web3, I get the `Unhandled rejection BigNumber Error: new BigNumber() not a number: [object Object]` which seems to occur on invalid deserializations when the ABI doesn't match what's being returned from the contract.

If I write my own getter

    function getIdsForContract(address _contractAddress) returns (uint256[]) {
        return idsForContract[_contractAddress];
    }

The ABI for this method is correct with `uint256[]` as the output type, and invoking through web3 works correctly.

## Steps to Reproduce

1. `truffle init`
2. Open `MetaCoin.sol` and add the line `mapping (address => uint256[]) public myMapping;`
2. Run `truffle build`
3. Look at the Contracts.all_networks object in build/app.js for myMapping's generated getter.
4. See if it has an output with type `uint256` instead of `uint256[]`.

## Expected Behavior

Output type should be `uint256[]`.

## Actual Results

Output type is `uint256`.

Examples listed above, with the main symptom being that web3 can't deserialize return value from the getter via `contractObject.myMapping.call(....)`

## Environment

* Operating System: OS X 10.11.4
* Truffle version: 2.1.1
* Ethereum client: Geth 1.4.18
* node version: 4.6.0
* npm version: 2.15.9

**Comment by tcoulter** [comment]
This ABI interface isn't created by Truffle. Instead, it's created by the `solc` compiler. Solidity doesn't create a function for you that returns an array; instead, it creates a function that takes (in this case) an address as the input and returns the associated uint256 based on the mapping. Calling this function might look something like this:

```javascript
contractObject.myMapping.call("0x1234...") // => 5
```

Because Solidity creates this function and ABI, there's nothing Truffle can do about it. This isn't a Truffle issue, and is instead "as designed" by the Solidity language designers. Please bring an issue up with them if you believe this to be incorrect.

**Comment by dob** [comment]
Thanks. Figured it may be a solc issue, so I'll hunt down where to bring that up with them. I don't understand the design decision that a `mapping (address => uint[])` would return "an associated uint", since the address is clearly associated with an array of uint and not a single one.

**Comment by tcoulter** [comment]
Oh wow. I didn't actually see that the mapping mapped addresses to a uint array. I admittedly wrote this hastily. Thanks for bringing this up.

My hunch is that the above is still correct, in that this is not a Truffle issue. Truffle never generates or modifies ABIs, so this has to come from a solidity compiler. However, I'm not sure what it should do in this case. 

It might actually create a function that takes in two parameters, like so:

```javascript
contractObject.myMapping.call("0x1234...", 7) // => 5
```

Where the `7` is the array index of the array specified by the address in the mapping. This is my hunch.

**Comment by dob** [comment]
Wow, just tested it and you're right

    tap.idsForContract.call("0x131bec75342a54ffea3087bda5ba720394c486a9", 0).then(function(res){ console.log(res.toNumber())}) // => 5

I didn't expect that, since I didn't see a second argument to a getter documented anywhere...but there it is in the ABI. 

    "inputs": [
          {
            "name": "",
            "type": "address"
          },
          {
            "name": "",
            "type": "uint256"
          }
        ],

So I guess the pattern is to call some sort of `getLengthForAddress(address)` function first, and then make successive calls for each element in the array. Thanks.

**Comment by mattlockyer** [comment]
You can make a constant function that returns the array, this will allow you to get the whole array in one shot:

function getIndicies() constant returns (uint256[]) {
    return indicies[msg.sender];
  }

Note: only the type uint can be returned as an array

**Comment by ferittuncer** [comment]
This bug still exists in 0.4.24.

**Comment by ferittuncer** [comment]
@dob @tcoulter It doesn't work when second argument is not `0`. I get invalid opcode error.
