### ISSUE TITLE
Why migrate stuck here.

### ISSUE THREAD

**Issue by 350050183** [ConsenSys/truffle#305]
- [Y] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I run the official example code: truffle migrate,and stuck there for a long long time:

#truffle migrate
Running migration: 1_initial_migration.js
  Deploying Migrations... 

If i delete the deploy steps in the 1_initial_migration.js and 2_deploy_contracts.js, it runs fine.
I run geth in a test private network with command like

**geth --identity "CSQNodeName" --rpc --rpcport "8080" --rpccorsdomain "*" --datadir ~/.ethereum_private --port "30303" --nodiscover --rpcapi "db,eth,net,web3" --networkid 1999 --unlock "0x60249051528212bd2fd0e72933b5931836065b56" console**

and has changed the truffle.js port to 8080.

## Steps to Reproduce

1.geth --identity "CSQNodeName" --rpc --rpcport "8080" --rpccorsdomain "*" --datadir ~/.ethereum_private --port "30303" --nodiscover --rpcapi "db,eth,net,web3" --networkid 1999 --unlock "0x60249051528212bd2fd0e72933b5931836065b56" console
2.mkdir helloworld && cd helloworld && truffle init
3.truffle compile
4.truffle migrate

## Expected Behavior

finish migrate.

## Actual Results

stopped and nothing happened for a long time.

## Environment

* Operating System: os x
* Truffle version:2.1.0
* Ethereum client:1.4.17
* node version:5.0.0.
* npm version: 3.3.6

**Comment by webpolis** [comment]
Same here... it seems there initial transactions coming from the migrate script get stuck in the *pending* queue

**Comment by webpolis** [comment]
Mmh.. I think I'm moving to Embark - https://github.com/iurimatias/embark-framework - .. too many open issues here, no response and buggy framework :(

**Comment by webpolis** [comment]
If I enable the *verboseRpc* (true) in _truffle.js_, I see a lot of this:

```
   > [
   >   {
   >     "jsonrpc": "2.0",
   >     "method": "eth_getFilterChanges",
   >     "params": [
   >       "0x83472eda6eb475906aeeb7f09e757ba9"
   >     ],
   >     "id": 79
   >   }
   > ]
 <   [
 <     {
 <       "jsonrpc": "2.0",
 <       "id": 79,
 <       "result": []
 <     }
 <   ]
```

And the Ethereum console doesn't show any mining activity. I thought Truffle will be in charge of "cooking" up the transactions.

**Comment by 350050183** [comment]
It's holiday season,haha,be paitient:)

**Comment by webpolis** [comment]
@350050183 I'm so f*cking inspired right now lol.. a really nice project I'm working on

**Comment by ETHorHIL** [comment]
Did anyone find out how to solve this?

**Comment by tcoulter** [comment]
It appears that your geth RPC port is 8080. Truffle defaults to looking for
an Ethereum client on 8545. You need to edit your truffle configuration to
point to the port you specified.
http://truffleframework.com/docs/advanced/configuration under heading "RPC"

**Comment by tcoulter** [comment]
Hmm, looks like I misread. Let me think.

**Comment by ETHorHIL** [comment]
The Problem in my case was that Parity was running in the background. When I kill the process it works.

**Comment by chrc** [comment]
Hello,

I am the same problem. Any solution ?

**Comment by rajaboini525** [comment]
Hello,

I am also facing the same issue. Any solution ?

**Comment by tcoulter** [comment]
This is an issue best worked out through our gitter channel, since everyone's configuration is different. Please join the channel and ask there. We have over 700 active members willing to help. Cheers! https://gitter.im/ConsenSys/truffle

**Comment by baoit09** [comment]
For me, what I need to do to overcome this stuck is remove the DAG file. Then, every things works fine.

**Comment by sk4092** [comment]
where can I find DAG file in windows 7.

**Comment by Almaju** [comment]
I just ran into the exact same problem and it was due to two nodes being on the port (30303). It worked like a charm after stopping one!

**Comment by parag** [comment]
Shutting parity if that is working in the background will help

**Comment by shohel02** [comment]
I am facing the same issue. I am running geth testnet node against which i am running 'truffle migrate' .  Both the migrate and geth node hangs after this.  Tried with DAG delete, does not work. Anyone find solution for this

**Comment by ewerton-azevedo** [comment]
I could solve that running miner.start() in another console window.

**Comment by arielgabizon** [comment]
@parag I don't understand - if I shut parity then it crashes - it needs some client to work with to deploy the contract doesn't it?

**Comment by amrikmahal** [comment]
Hi, Was having the same problem where migration was stuck.
ran miner.start() through to web3 console and the contract was migrated. 

 I believe the contract is not getting mined, the moment, miner.start() is fired, i could see the mining nodes picked up the contract.  Not sure what is wrong here, but this workaround worked.

**Comment by y0unghe** [comment]
miner.start solved it. that's really odd.

**Comment by moda20** [comment]
I am having this problem with quorum, and even when running miner.start() it doesn't work instantly. uses all CPU on generating DAG and then nothing happens.
help
