### ISSUE TITLE
Update solc to minimum 0.4.5.

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/truffle#308]
0.4.5+ fixes a issue in the Solidity compiler where it incorrectly would throw inline assembly warnings. I had to build a custom Truffle to ignore this.

I asked Christian to update solc on npm to 0.4.6 (https://github.com/ethereum/solc-js/issues/74), but somehow stopped short at 0.4.5. However, 0.4.5 has this fix so that I don't have to run a custom Truffle anymore to those warnings.

If npm updates to 0.4.6, I'll update the beta to 0.4.6 and submit a PR as that is the branch I'm currently using.

**Comment by simondlr** [comment]
Seems npmjs site is out of date. npm view solc shows that 0.4.6 is the latest. I'll get round to a PR to beta.

**Comment by tcoulter** [comment]
This has been done on beta. Clsoing.
