### ISSUE TITLE
issues on windows 10 regard to CovertLib.sol

### ISSUE THREAD

**Issue by rfikki** [ConsenSys/truffle#312]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
In the beta version truffle init works fine, but truffle compile has a problem with locating the files due to error in directory structure with the "/":
truffle compile
Compiling ./contracts\ConvertLib.sol...
Compiling ./contracts\MetaCoin.sol...
Compiling ./contracts\Migrations.sol...
Error compiling:
C:\projects\truffle-dapps\beta-test\contracts\MetaCoin.sol:3:1: Error: Source "ConvertLib.sol" not found: File not supplied initially.
import "./ConvertLib.sol";
^------------------------^
Compiliation failed. See above.

## Steps to Reproduce

truffle compile the default dapp

## Environment

* Operating System:  Win64 10
* Truffle version: 3.03 beta
* Ethereum client: latest geth
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8

**Comment by Adonis2115** [comment]
I am facing exactly same issue. Please share solution if you find one.

**Comment by Adonis2115** [comment]
@tcoulter  can you help?

**Comment by tcoulter** [comment]
I've fixed this on 3.0.0-7 beta. There was an accidental release that that caused 3.0.0-x to be published as the latest version of npm. If you do intend to be on the beta version, upgrade to 3.0.0-7. If not, you should downgrade to 2.1.1.

Sorry for the confusion!

**Comment by tcoulter** [comment]
Whoops, make that 3.0.0-8 beta, which I'm releasing now.
