### ISSUE TITLE
getData undefined for methods

### ISSUE THREAD

**Issue by gnom1gnom** [ConsenSys/truffle#323]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

getData is not available for a method.
I need it for `web3.eth.sendTransaction`
Instead in my truffle test I have to call 
```
var metaWeb3 = web3.eth.contract(meta.abi);
var metaWeb3Instance = metaWeb3.at(meta.address);
var getBalanceData = metaWeb3Instance.getBalance.getData(accounts[1]);
```

## Steps to Reproduce
```
var meta = MetaCoin.deployed();
var getBalanceData = meta.getBalance.getData(accounts[1]);
```

## Expected Behavior
Return the byte string.

## Actual Results
TypeError: meta.getBalance.getData is not a function

## Environment

* Operating System: Windows 7 Sp1
* Truffle version: v2.1.1
* node version: 6.9.2
* npm version: 3.10.9

**Comment by tcoulter** [comment]
In the example above, `meta` is already contract abstraction, provided by `ether-pudding`. Pudding's abstractions are an extension of `web3.eth.contract()`.

To call the `getBalance()` function, you need merely write:

```
meta.getBalance(address).then(function(balance) {
  // Do something with the balance
}).catch(function(e) {
  // handle any error
});
``` 

The above will send the transaction; you do not need to call `web3.eth.sendTransaction()`  yourself. Since Pudding wraps these functions in promises, you'll have to interact with them that way like the above. For more information, see the documentation here: http://truffleframework.com/docs/getting_started/contracts

I'm going to close this ticket as Truffle provides all this functionality for you and you don't need to do this yourself.

**Comment by gnom1gnom** [comment]
Sorry to repost, but perhaps I did not make myself clear. In my test case I try to check if event is generated.
```
it('SN is generating SNassigned event', function(done) {
	var myMyContract = MyContract.deployed();
	var MyContractEvents = myMyContract.allEvents();
	var inputID = "R051239874560002";

	MyContractEvents.watch(function (error, result) {
		if(error) {
			console.err(error);
		} else {
			console.log("SNassigned callback: " + result.args.sn.valueOf());
			assert.equal(result.event, "SNassigned");
			assert.equal(result.args._sender.valueOf(), web3.eth.accounts[0]);
			assert.equal(result.args.sn.valueOf(), inputID);
			MyContractEvents.stopWatching();
			done();
		}
	});

	var myMyContractWeb3 = web3.eth.contract(myMyContract.abi);
	var myMyContractWeb3Instance = myMyContractWeb3.at(myMyContract.address);
	var assignIDCallData = myMyContractWeb3Instance.assignID.getData(inputID);

	web3.eth.sendTransaction({
		from: web3.eth.accounts[0],
		to: myMyContract.address,
		data: assignIDCallData
	});
});
```
If I use `myMyContract.assignID(assignID)` _SNassigned_ event is not caught in watch handler. The above code works with `web3.eth.sendTransaction`

**Comment by tcoulter** [comment]
Are you using Truffle beta?

**Comment by gnom1gnom** [comment]
No. Truffle 2.1.1

**Comment by tcoulter** [comment]
Your code can be rewritten like the following. Note Truffle provides `accounts` for you from the `contract` block, so I'll include that for example purposes:

```
contract("MyContract", function(accounts) {
    // ...
    it('SN is generating SNassigned event', function(done) {
	var myMyContract = MyContract.deployed();
	var MyContractEvents = myMyContract.allEvents();
	var inputID = "R051239874560002";

	MyContractEvents.watch(function (error, result) {
		if(error) {
			console.err(error);
		} else {
			console.log("SNassigned callback: " + result.args.sn.valueOf());
			assert.equal(result.event, "SNassigned");
			assert.equal(result.args._sender.valueOf(), web3.eth.accounts[0]);
			assert.equal(result.args.sn.valueOf(), inputID);
			MyContractEvents.stopWatching();
			done();
		}
	});

        myMyContract.assignID(inputID, {from: accounts[0]}).then(function() {
            // This fires off a promise, but we're doing nothing with the result.
            // We include an empty `then()` block to ensure the promise gets evaluated.
        }).catch(done);
    });
});
```

**Comment by gnom1gnom** [comment]
Thank you! It works.

**Comment by rawadrifai** [comment]
@tcoulter - if I want to send a raw tx, how do I get the data value?
I think getData should work but it's not for me.

**Comment by mad2sm0key** [comment]
@rawadrifai Take a look at [#381](https://github.com/trufflesuite/truffle/issues/381) and [#10](https://github.com/trufflesuite/truffle-contract/issues/10)
