### ISSUE TITLE
Best practices regarding deployment

### ISSUE THREAD

**Issue by roderik** [ConsenSys/truffle#330]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I created a nice DAPP (react) on top of a smart contract and used the truffle solidity loader for webpack during development. Worked great with redeploys on testrpc whenever I changed anything.

But now I'm trying to deploy to something close to production, and I'm running into some issues. If I run the webpack build command, it compiles and deploys to the ropsten network using infura (ci build on circleci but also locally). Which is fine for the first time, but each build redeploys the contracts. I tried keeping the temporary artifacts between runs, but they just get deleted on build. 

So I'm wondering what the best practice is in this scenario. I feel like the solidity loader in "production mode" should check if the contracts are deployed or not and leave them alone in some way. Or store the deployed contact addresses in the truffle.js file and fill up the sol.js files using those values. Probably with some change detection?

Then again, I cannot be the only one wanting to run something on the testnet and rebuilding their frontend every now and then. I got pointed to more [manual scripts](https://github.com/swarmcity/ac-token/blob/master/deploy.js), but that seems like a step back.

## Environment

* Operating System: OSX / Ubuntu / Docker
* Truffle version: 2.1.1
* truffle-solidity-loader: 0.0.8
* Ethereum client: infura
* node version: 7.4
* npm version: 4.0.5 / yarn 0.18.1

**Comment by roderik** [comment]
Solved in the new version, disregard!

**Comment by ryana** [comment]
@roderik great explanation and thank you for filing this issue and self-closing.

I came into this after Feb 5, so I've only ever known a world where this solution exists, so to enlighten me could you either explain or point me to an explanation of what this solution was? My hunch is that before Feb 5, the `build/contracts` directory didn't exist, and adding it fixed your problem.

I'm running into a related problem which is that multiple contributors to a dapp keep overwriting parts of build/contracts files each time they deploy to their local testrpc. I'd like some way to keep the behavior you were initially seeking, but also ignore local deployment changes if possible to avoid messy commit histories.

**Comment by roderik** [comment]
I would suggest giving everyone's ganache an unique network id. That way they should not conflict.
