### ISSUE TITLE
Solidity tests pass when they shouldn't

### ISSUE THREAD

**Issue by LogvinovLeon** [ConsenSys/truffle#340]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Solidity tests do not seem to test anything. They just pass

## Steps to Reproduce

* `truffle init`
* Edit a `TestMetacoin` and change 10000 to smth (for example 42)
* `truffle test`

## Expected Behavior

Tests should fail

## Actual Results

Tests passed

## Environment

* Operating System: macos
* Truffle version: 3.0.2
* Ethereum client: testrpc
* node version: v7.5.0
* npm version: 4.1.2

**Comment by tcoulter** [comment]
This was due to the same underlying issue in #339, and has now been fixed. Thanks again for reporting this. Uninstall truffle and reinstall it again to update the latest dependencies. 

Cheers!
