### ISSUE TITLE
No way to provide mocha command-line options

### ISSUE THREAD

**Issue by raineorshine** [ConsenSys/truffle#346]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The way that truffle runs mocha disallows `babel-core/register` and `babel-polyfill` (needed for async/await, e.g.). This functionality [cannot be achieved with mocha's programmatic options](https://github.com/mochajs/mocha/issues/1220).

`truffle test` used to provide `--` as a way to pass arguments to mocha, iirc. That appears to not be possible any more.

## Steps to Reproduce

```sh
truffle test -- --compilers js:babel-core/register
```

I am using a babel config of:
```js
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "transform-async-to-generator"
  ]
}
```

## Expected Behavior

Tests should run with babel's runtime transformations.

## Actual Results

```
Using network 'development'.

  0 passing (1ms)
```

## Possible Solution

Presumably being able to pass command line arguments through to mocha would fix the issue, so that truffle test would behave like `mocha --compilers js:babel-core/register`.

Alternatively, adding these two lines of code to truffle's `./cli.js` solves the problem:

```js
require('babel-core/register')
require('babel-polyfill')
```

Obviously not every user wants this, so it would have to be conditional. What would be the best way to re-enable this functionality? Thanks!

## Environment

* Operating System: OSX
* Truffle version: 3.1.1
* Ethereum client: N/A
* node version: 7.0.4
* npm version: 4.0.5

**Comment by tcoulter** [comment]
Have your tried adding the babel-register `require` in your truffle.js
file? Truffle relied on babel previously but it caused more harm than good.
I'd prefer not making babel a dependency of Truffle.

**Comment by tcoulter** [comment]
Also, Truffle doesn't call mocha via the command line. Instead, it does it
programmatically. You can alter the mocha configuration via the `mocha` key
in your Truffle configuration file.
http://truffleframework.com/docs/advanced/configuration#mocha

**Comment by raineorshine** [comment]
It works! 😃

**Comment by tcoulter** [comment]
Yay! I need to write docs for this use case...

**Comment by tomerweisman** [comment]
@raineorshine 
Hi. can you please provide the truffle.js, or any configuration files that worked for you?

**Comment by cgewecke** [comment]
@tomerweisman Here's an example that tells mocha to consume a third-party reporter. Equivalent to:
```shell
mocha --reporter <reporter-name> --reporter-options <options>
```

```javascript
module.exports = {
  networks: {
    ...etc...
  },
  mocha: {
    reporter: 'super-test',
    reporterOptions : {
      extraEmojis: false,
    }
  }
};
```

**Comment by tomerweisman** [comment]
@cgewecke this for the example. my problem is that I cant get truffle (mocha) to recognize ES6 "import" syntax. 
Ive added the following dependencies in **package.json**:
`"devDependencies": {
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "babel-register": "^6.26.0",
    "solidity-coverage": "^0.5.0"
  }`

and have this **.babelrc** file: 
`{
  "presets": ["es2015", "stage-2", "stage-3"]
}`

and **truffle-config.js** file:
`require('babel-register')({
    ignore: /node_modules\/(?!zeppelin-solidity)/
});
require('babel-polyfill');`


Truffle v4.1.8 (core: 4.1.8)
Solidity v0.4.23 (solc-js)

I wanted @raineorshine to share the config files that worked for her
Any idea how to solve? 

thanks

**Comment by mtomov** [comment]
Hey @tomerweisman  - thanks so much - your `truffle-config.js` example totally allowed me to do the same thing you're after!

I have the same `.babelrc` and `package.json` files, but placed the `require('babel..` in `truffle.js` instead.

Try changing `zeppelin-solidity` to `openzeppelin-solidity` as well. 

Thanks again!

**Comment by rrthomas** [comment]
I found this issue while trying to get source map support to work with `nyc` while wrapping `truffle test`.

It seems that although you can add `require` as a key in a mocha configuration file, you cannot use it as part of an `options` object passed to `new Mocha()`, which is how truffle uses its settings object; at least, it is not documented in the list at https://mochajs.org/api/mocha#Mocha, and if I add a setting like `"require": "non-existent-module"` to my `mocha` settings object in `truffle-config.js`, I don't get an error, which suggests that the setting is not used.

Adding the programmatic invocation of `source-map-support` as documented at https://www.npmjs.com/package/source-map-support, namely, `require('source-map-support').install();` to `truffle-config.js` does not work either.

(I have checked that nyc is generating source maps!)
