### ISSUE TITLE
"truffle console" fails immediately after "truffle init"

### ISSUE THREAD

**Issue by MichaelMaurer** [ConsenSys/truffle#352]
## Issue

If you run `truffle console` immediately after `truffle init`, it fails complaining that the `build/contracts` directory is missing. You must run `truffle compile` first.

## Steps to Reproduce

$ truffle version
$ truffle init
$ truffle console

## Expected Behavior

The console should start up.

## Actual Results

    $ truffle version
    Truffle v3.1.1

    $ truffle init
    Downloading project...
    [...]

    $ truffle console
    Enexpected error: Cannot provision contracts while instantiating the console.
    Error: ENOENT: no such file or directory, scandir '/Users/.../.../build/contracts'
    truffle(development)> TypeError: Cannot read property 'forEach' of undefined
        at TruffleInterpreter.resetContractsInConsoleContext (/usr/local/lib/node_modules/truffle/lib/repl.js:95:17)
        at /usr/local/lib/node_modules/truffle/lib/repl.js:44:12
        at /usr/local/lib/node_modules/truffle/lib/repl.js:58:21
        at FSReqWrap.oncomplete (fs.js:111:15)

(Also note the spelling typo in the error message.)

## Environment

* Operating System: Mac OS X 10.11.6
* Truffle version: 3.1.1
* Ethereum client: TestRPC
* node version: 7.2.0
* npm version: 3.10.9

**Comment by tcoulter** [comment]
Thanks for the report. This has been fixed on master and will go out in the next release! Appreciate it!

**Comment by elenadimitrova** [comment]
I am getting something similar here with `truffle@3.1.9` but even after `truffle compile`

```
$ truffle version
Truffle v3.1.9
$ truffle compile
$ truffle console
Enexpected error: Cannot provision contracts while instantiating the console.
Error: Cannot parse .DS_Store: Unexpected token 
    at /Users/Elena/.nvm/versions/node/v4.6.1/lib/node_modules/truffle/lib/repl.js:69:27
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
truffle(development)> TypeError: Cannot read property 'forEach' of undefined
    at TruffleInterpreter.resetContractsInConsoleContext (/Users/Elena/.nvm/versions/node/v4.6.1/lib/node_modules/truffle/lib/repl.js:95:17)
    at /Users/Elena/.nvm/versions/node/v4.6.1/lib/node_modules/truffle/lib/repl.js:44:12
```

**Comment by nammzzi** [comment]
hi I am getting the same error as @elenadimitrova I do truffle compile, truffle migrate then truffle console. Updated to latest truffle version. Can someone help
