### ISSUE TITLE
"truffle init" should check for existence of truffle.js before messing up with the current dir

### ISSUE THREAD

**Issue by gapar2** [ConsenSys/truffle#356]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

"truffle init" will screw up your working directory

## Steps to Reproduce

Have a working truffle workspace with a bunch of stuff in it. 

## Expected Behavior

"truffle init" does nothing, e.g., does not add MetaCoin.sol, and perhaps prompt you "The current directory already contains a truffle.js, skipping..."

## Actual Results

Adds MetaCoin.sol to contracts and generally mess up your workspace

## Environment
All

**Comment by tcoulter** [comment]
Added to truffle-init in v1.0.5. To enable, uninstall and reinstall Truffle, which will download the latest truffle-init dependency. Cheers!
