### ISSUE TITLE
Can't compile solidity assembly from truffle

### ISSUE THREAD

**Issue by maraoz** [ConsenSys/truffle#360]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Contracts with solidity assembly won't compile. 

## Steps to Reproduce

1. clone this repo: https://github.com/maraoz/lib
2. run `truffle test`

## Expected Behavior
Contracts should compile.

## Actual Results

```
maraoz@sakugawa:~/git/lib$ truffle version
Truffle v3.1.9
maraoz@sakugawa:~/git/lib$ truffle test
Compiling ./contracts/Migrations.sol...
Compiling ./test/TestProxyLibrary.sol...
Compiling truffle/Assert.sol...

/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/index.js:39
      throw e;
      ^
SyntaxError: Expected "=:", "hex", "let", "{", "}", comment, end of line, number, string, or whitespace but "r" found.
    at peg$buildStructuredError (/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/build/parser.js:1272:12)
    at Object.peg$parse [as parse] (/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/build/parser.js:13858:11)
    at Object.parse (/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/index.js:34:23)
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-solidity-utils/index.js:15:32
    at tryToString (fs.js:425:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12)

```
## Environment

* Operating System: Ubuntu
* Truffle version: Truffle v3.1.9
* Ethereum client: testrpc
* node version: v7.3.0
* npm version: 3.10.10

**Comment by tcoulter** [comment]
So things are looking good over here - I think Truffle 3.1.9 fixes this issue. If not 3.1.9, then the latest master: https://github.com/ConsenSys/truffle/commit/ba6f73f092f8c5804ac7b1e7d15dc2ce7712ebaf

Check out my gist. I had to add a migration, but otherwise your tests pass (with some extra output it looks like): 
https://gist.github.com/tcoulter/752452d71f72acbc8bff155863194c58

Can you try this and see if you get the same results: 

```
$ npm uninstall -g truffle
$ git clone https://github.com/ConsenSys/truffle.git
$ cd truffle
$ npm install -g .
```

**Comment by maraoz** [comment]
works!
