### ISSUE TITLE
EPM deployment fails with Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by JackBekket** [ConsenSys/truffle#361]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

EPM deployment fails with "Insufficient funds for gas * price + value". Try through INFURA.

## Steps to Reproduce
1. Check out this repo (https://github.com/JackBekket/EthPM)
2.
    Add a secrets.json file to the root directory. The secrets.json file can be:
```
{
  "mnemonic": "decide neither mix slide theme sad ladder fault awkward program guide deposit"
}
```
3. run ```npm install &&truffle publish ```

## Expected Behavior

The EPM package to publish successfully.

## Actual Results

Error: Insufficient funds for gas * price + value

## Environment

* Operating System: Ubuntu 16.04
* Truffle version: 3.1.1
* Ethereum client: INFURA Ropsten
* node version: 7.5
* npm version:  4.2.0

**Comment by tcoulter** [comment]
This appears to be a dupe of #354 (even down to your hdkey mnemonic). Is that correct?

**Comment by tcoulter** [comment]
Hmm, actually, looks like you're receiving slightly different errors.

**Comment by JackBekket** [comment]
@tcoulter 
I found out source of problem -bug with parity and their mnemonic phrase. Any mnemonic from parity is not work.

**Comment by yyd106** [comment]
Hi, I'm facing the same issue, do you have any update on the fixing?
