### ISSUE TITLE
Unable to install truffle

### ISSUE THREAD

**Issue by amithanamakkanavar** [ConsenSys/truffle#364]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

npm ERR! git fetch -a origin (https://github.com/debris/bignumber.js) fatal: unable to access 'https://github.com/debris/bignumber.js/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received
npm ERR! Error: Command failed: fatal: unable to access 'https://github.com/debris/bignumber.js/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received

**Comment by tcoulter** [comment]
This looks like a network issue. I'd tried again. This isn't a problem with Truffle, and is either due to your network configuration or node/npm configuration.

**Comment by amithanamakkanavar** [comment]
Now am getting error as

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "truffle"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, statusCode=407
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/****/npm-debug.log

**Comment by tcoulter** [comment]
This is definitely a network issue, and not a Truffle issue - because of
that, it's too hard for me to help. Please google the error message to
figure out the problem.
