### ISSUE TITLE
contracts.json relative paths for contract source

### ISSUE THREAD

**Issue by ethers** [ConsenSys/truffle#37]
currently the contracts.json from a `truffle compile` produces a json where the value of `source` is an absolute path.  a disadvantage is that everyone would have a different local path to the contract (and is also OS dependent, like /Users/tim/contract.sol  vs  /home/tim/contract.sol)

i am just starting out with truffle, but if relative paths could be used like `./contract.sol` then teams could easily work from the same repo

**Comment by tcoulter** [comment]
This is a great report, thanks. I'll make sure to change it.

**Comment by tcoulter** [comment]
Fixed in the latest commit. Closing!

**Comment by wcc21320** [comment]
where is it, the location of "contracts.json" ?
