### ISSUE TITLE
Toward one command development

### ISSUE THREAD

**Issue by taoeffect** [ConsenSys/truffle#38]
Currently the docs state you can "easily swap" TestRPC for `geth` or `eth`:

> Though we suggest you use the TestRPC during development, you can easily swap it out for geth or eth and re-run your tests without changing a single line of code.

While this is technically true, in practice it is not so easy, and if you count the command-line voodoo that's required in a separate terminal as "a single line of code", then this claim is misleading at best.

The developer must be aware of the ins and outs of `geth` to be able to do this, and from my understanding of Embark it is by no means trivial to setup `geth` in a fake dev mode.

Ideally, you'd be able to do the following:

```
truffle serve --geth
```

And `tuffle`, like Embark, would setup and run geth for you. Right now, however, the developer must know how to run `geth` themselves in a way that does not put their account balances at risk.

If instead, you could just specify the EVM source via `truffle serve --testrpc` (or something like that), and have truffle do all the work of setting everything up safely and cleaning up after itself when it's done, then development would be so much simpler, safer, and smoother.

**Comment by taoeffect** [comment]
(I'm not entirely sure what the CLI flag needs to look like, maybe `--evm=geth` would be better.)

**Comment by tcoulter** [comment]
Thanks for your comment.

> Right now, however, the developer must know how to run geth themselves in a way that does not put their account balances at risk.

I can see the usefulness, but if you're running Truffle against the live network, I think this is important knowledge. Why trust Truffle to do it right? 

That said, I'm going to close this as as of Embark 1.0.2 Truffle and Embark no longer have philosophical differences, and will eventually merge efforts in the long run. We can leave this feature to the eventual merge.

**Comment by taoeffect** [comment]
> Truffle and Embark no longer have philosophical differences, and will eventually merge efforts in the long run.

That's fantastic news! Congratulations!! :smile: :+1: 

> We can leave this feature to the eventual merge.

I believe Embark already has this feature (or something similar)?
