### ISSUE TITLE
Truffle should ignore non-development files.

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/truffle#40]
Truffle picks up VIM buffer files (*.swp) and other files such as (.DS_Store) when running tests, which causes it to break. Only sol & se should probably be allowed at this point.

Similarly with the tests themselves, it also does the same. Perhaps only javascript files should be allowed in that scenario.

**Comment by HCharlanes** [comment]
I have to run in a terminal
`sudo find / -name ".DS_Store" -depth -exec rm {} \;` 
every time I want to run tests. What are guys your trick ?

**Comment by kayagoban** [comment]
I'm on Truffle v3.1.9 and I still have this problem with .swp files from vim.  Ideas?
