### ISSUE TITLE
 inject-contracts post-processor don't work in node environment

### ISSUE THREAD

**Issue by mhhf** [ConsenSys/truffle#41]
Currently, if an empty file is post processed with "inject-contracts" it works in the browser, but not in the node environment, because the window dependent code is not wrapped:

Currently the output file looks like this:
```
// If we're in the browser, call the helpers using the global
// (window) scope. If we're in node, export the helpers as a module.
if (module != null) {
  module.exports = __provisioner;
}
__provisioner.provision_contracts(window);

/* code */

; __provisioner.set_provider(window);
```

When it should look like this:
```
// If we're in the browser, call the helpers using the global
// (window) scope. If we're in node, export the helpers as a module.
if (module != null) {
  module.exports = __provisioner;
} else {
  __provisioner.provision_contracts(window);
}


; if( module == null ) {
  __provisioner.set_provider(window);
}
```

**Comment by tcoulter** [comment]
Hi @mhhf. Are you familiar with the `asModule()` function of the provisioner? https://github.com/ConsenSys/truffle/blob/master/lib/provision.es6#L29

What context are you trying to use this code in? Can you tell me more about what you're trying to do?

**Comment by mhhf** [comment]
I'm trying to clean up [spore](https://github.com/mhhf/spore)s build-chain. It's command line based and I'd like to manage different chains (local, consensys-testnet, main) with truffle. I need a way to inject the current environment code (host, port) and compiled contracts into the spore cli code.

I guess I'll have to write a custom post-processor for this?!

**Comment by tcoulter** [comment]
Hmm. Is there any code of yours I can see? If you run `truffle build -e consensys-testnet`, where consensys-testnet is an environment set up within your config directory, then it'll inject the contracts from that environment.

Check out Myth 7 on this post here: https://medium.com/@timothyjcoulter/truffle-tricks-for-ethereum-development-dispelling-8-myths-first-impressions-880f66bf3320

**Comment by tcoulter** [comment]
Get on the consensys slack and let's chat about this! Would love to help if the above doesn't work out.

**Comment by tcoulter** [comment]
Update on this. Use the newly added `include-contracts` processor instead of `inject-contracts`. Note that with the new release of Truffle coming today, `inject-contracts` has been renamed to `bootstrap`.
