### ISSUE TITLE
truffle init problem

### ISSUE THREAD

**Issue by m888m** [ConsenSys/truffle#48]
After installing truffle, and trying to launch it with truffle init, I get the following errors:

    m@888@m:~/dmc/truffleTest$ npm rebuild node-sass

    > node-sass@3.4.1 install /home/m/dmc/node_modules/node-sass
    > node scripts/install.js

    > node-sass@3.4.1 postinstall /home/m/dmc/node_modules/node-sass
    > node scripts/build.js

    ` /home/m/dmc/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists. 
     testing binary.
    Binary is fine; exiting.
    node-sass@3.4.1 /home/m/dmc/node_modules/node-sass
    m@888@m:~/dmc/truffleTest$ truffle init
    Error: The `libsass` binding was not found in /home/m/npm-global/lib/node_modules/truffle/node_modules/node-sass/vendor/linux-x64-46/binding.node
    This usually happens because your node version has changed.
    Run `npm rebuild node-sass` to build the binding for your current node version.
      at Object.sass.getBinaryPath (/home/m/npm-global/lib/node_modules/truffle/node_modules/node-sass/lib/extensions.js:158:11)
      at Object.<anonymous> (/home/m/npm-global/lib/node_modules/truffle/node_modules/node-sass/lib/index.js:16:36)
      at Module._compile (module.js:435:26)
      at Module._extensions..js (module.js:442:10)
      at Object.require.extensions.(anonymous function) [as .js] (/home/m/npm-global/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
      at Module.load (/home/m/npm-global/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:311:12)
      at Module.require (module.js:366:17)
      at require (module.js:385:17)
      at Object.<anonymous> (/home/m/npm-global/lib/node_modules/truffle/lib/processors/scss.es6:3:12)
      at Module._compile (module.js:435:26)
      at normalLoader (/home/m/npm-global/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
      at Object.require.extensions.(anonymous function) [as .es6] (/home/m/npm-global/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
      at Module.load (/home/m/npm-global/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:311:12)
      at Module.require (module.js:366:17)
      at require (module.js:385:17)
      at Object.gather (/home/m/npm-global/lib/node_modules/truffle/lib/config.es6:227:38)
      at /home/m/npm-global/lib/node_modules/truffle/truffle.es6:150:23
      at /home/m/npm-global/lib/node_modules/truffle/node_modules/deasync/index.js:35:6
      at runTask (/home/m/npm-global/lib/node_modules/truffle/truffle.es6:55:5)
      at Object.<anonymous> (/home/m/npm-global/lib/node_modules/truffle/truffle.es6:347:14)
      at Module._compile (module.js:435:26)
      at normalLoader (/home/m/npm-global/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
      at Object.require.extensions.(anonymous function) [as .es6] (/home/m/npm-global/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:311:12)
      at Function.Module.runMain (module.js:467:10)
      at Object.<anonymous> (/home/m/npm-global/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)
      at Module._compile (module.js:435:26)
      at Object.Module._extensions..js (module.js:442:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:311:12)
      at Function.Module.runMain (module.js:467:10)
      at startup (node.js:134:18)
      at node.js:961:3

Note that before launching truffle, I did npm rebuild node-sass , but still get the corresponding error.
Please help

**Comment by tcoulter** [comment]
It looks to me like truffle wasn't properly install (i.e., an npm issue). Do an `npm uninstall -g truffle` and then an `npm install -g truffle` and see if that solves it.

**Comment by m888m** [comment]
Thanks a lot Tim! Solved it :+1:

**Comment by parvez99** [comment]
Hi Tim,

I am new to truffle and trying to build my first dApp. I have an Ubuntu 15.04 VM setup with Nodejs 5.10 and testrpc ethereum client installed as instructed on the website ( http://truffle.readthedocs.io/en/latest/getting_started/project/ ). 

After running $ npm install -g truffle when I execute truffle init, it does not seem to do anything at all . I am not able to understand what the problem is. Could you please tell me a few things that I could try. Thanks.

**Comment by Akiiki** [comment]
Hi Tim, Please share your screenshot. Also truffle creates the project folders and files in the directory you run the `truffle init `command. For example if I navigate to Documents using `cd Documents` in my terminal and run the `truffle init `command, It will create the project files in Documents folder

**Comment by parvez99** [comment]
Hi, Thanks for the response. I have it resolved. There were some persmission issues with the folder where I was executing truffle init command. But there's one thing that I notice different. I am follwing https://www.youtube.com/watch?v=GPP6uAq15d8 video where, at 1:54 there's a file called 'app.json' explained as very important for configuration purposes.. But after initializing truffle, I accessed the project in atom and do not see the file called app.json . Also there's no config folder instead there's an environment folder. Is this an upgrade change or am I missing something. please comment as it'd be helpful. Thanks

**Comment by danielrussellLA** [comment]
I had a similar problem. I ran `npm i -g truffle` and then when I tried to run `truffle init` I got an error: `zsh: command not found: truffle`.  What solved it for me is to create a local `node_modules` with truffle installed in it, and then run that copy.

1. run `npm init` and make a new npm project
2. run `npm i truffle`
3. run `./node_modules/.bin/truffle init` and it should work!

**Comment by drewesk** [comment]
@danielrussellLA thanks for something that works, turned that into an alias so I could pretend that I was directly running the truffle command like a real boy.

**Comment by danielrussellLA** [comment]
Glad it worked for you @drewesk!

**Comment by bisratyalew** [comment]
Hi, I am trying to build my first dApp. I am using windows 8 with Nodejs 6.11.1... I have installed truffle, testrpc properly but when i try to initialize truffle with "truffle init"... it didn't provide me MetaCoin.sol, ConvertLib.sol and others. why is this happening? Here's the screenshot 
![trufflegenerated](https://user-images.githubusercontent.com/30002154/35198575-bb58cb6a-fea5-11e7-9ffd-e3b31ecefa4d.jpg)

**Comment by vamshirapolu** [comment]
I had a problem with `truffle init`. I end up having an error 
```
Downloading...
Error: Error making request to https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js. Got error: connect ETIMEDOUT 151.101.20.133:443. Please check the format of the requested resource.
    at Request._callback (C:\Users\vrapolu\Work\tools\nodejs\.npm-global\node_modules\truffle\build\webpack:\~\truffle-box\lib\utils\unbox.js:45:1)
    at self.callback (C:\Users\vrapolu\Work\tools\nodejs\.npm-global\node_modules\truffle\build\webpack:\~\request\request.js:186:1)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\vrapolu\Work\tools\nodejs\.npm-global\node_modules\truffle\build\webpack:\~\request\request.js:878:1)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
```
I have tried uninstalling and installing truffle as @tcoulter mentioned, but now luck.

**Comment by cgewecke** [comment]
@vamshirapolu There's more about this problem over at #766.  At the moment `init` requires a working internet connection that can connect to github over `https`. If you're behind a proxy, you might see additional errors although there some work arounds suggested in that thread. 

Ultimately we should remove any network connectivity requirements for `truffle init`. Opening an issue to that effect right now.

**Comment by vamshirapolu** [comment]
Thanks @cgewecke for the quick reply. As suggested, I did a git clone of [truffle-init-default](https://github.com/trufflesuite/truffle-init-default), now its working fine.

**Comment by 0sk11** [comment]
I tried to unbox pet-shop (screenshot attached).It's says downloading... but the folder remains empty.
![dapp](https://user-images.githubusercontent.com/22243353/48305237-0c83b200-e54d-11e8-9578-ff14440486c1.PNG)

**Comment by RaynHarr** [comment]
I am getting stuck at the unbox command, any ideas would be much obliged:
![Screen Shot 2019-03-28 at 1 25 16 PM](https://user-images.githubusercontent.com/39592448/55180071-35ed5500-515f-11e9-99d7-61c477e82732.png)

**Comment by CruzMolina** [comment]
Hey @RaynHarr, can you see if `npx truffle@5.0.2 unbox pet-shop` works?

**Comment by RaynHarr** [comment]
Wow, @CruzMolina ! That worked, thanks! What did I do exactly?

**Comment by CruzMolina** [comment]
Nice. Have you tried uninstalling and installing truffle? (`npm uninstall -g truffle && npm i -g truffle@5.0.2`) 

`npx` is a package runner that temporarily downloads an npm package into a local cache and runs your package from there (https://www.npmjs.com/package/npx)

**Comment by CruzMolina** [comment]
Some users have reported issues in the past after using `sudo` to install and uninstall truffle, although maybe that's not something you've done.

Are you using a node version manager like `nvm` or `n`? Just trying to think off hand would else could be causing your issue.

**Comment by RaynHarr** [comment]
I did try to uninstall and reinstall, but was getting same result. 'Sudo' and 'nvm' or even 'n' are all not in my lexicon at this point, to show you how green I am. I must be missing something really basic and fundamental because I can't find anything on google about this and you're the first and only person to reach out after hours of scouring for some sort of clue. I really appreciate the quick fix!

**Comment by CruzMolina** [comment]
Huh. What version of node & npm are you using?

I can tell you're on a MacBookPro (I am too! macOS High Sierra 10.13.6), although I doubt what you're encountering is OS-specific.

Meanwhile, instead of having to use `npx` to download & then run truffle every time, you should be able to `npm i truffle@5.0.2` locally and then run `npx truffle <whateverCommand>`. Actually, I'd be interested in seeing if that works. It shouldn't download truffle again before running, instead it should just access what you locally installed in your local `node_modules` folder.

**Comment by RaynHarr** [comment]
node 10.15.3 and npm is 6.4.1. Using Sierra 10.12.6. I'm not entirely postiive I understand how to do it locally, but here's what I just tried, hopefully this provides some insight:
![Screen 1](https://user-images.githubusercontent.com/39592448/55245067-cdfb4500-5218-11e9-8529-e61ac972df0f.png)
![Screen 2](https://user-images.githubusercontent.com/39592448/55245068-cdfb4500-5218-11e9-999c-667d1bbdf498.png)

**Comment by CruzMolina** [comment]
Thanks for sharing that!

Looks like saving locally w/ npm & accessing the local `node_modules` truffle works.

I suspect something is incorrectly configured w/ npm global installations.

This troubleshooting tutorial _might_ be what you need: https://medium.com/@jagatjyoti.1si13cs040/npm-g-install-npm-package-not-working-as-desired-why-why-why-19795abf0b59

This should get you back on track and make `npm i -g truffle` work so you can just run truffle commands normally w/o npx (otherwise you would have to install truffle locally in every different truffle project directory 😭 )

**Comment by RaynHarr** [comment]
I'm a little confused. (a lot really) I'm staring at the 'compilation failed' script at the bottom. Am I missing something? Or is that where the article link you provided is supposed to help troubleshoot me out? I have to admit, the article is also going way over my head. Wondering if there's a more basic tutorial I should be going through to have a better understanding of what exactly is going on here? I'm trying to learn through these DAPP University videos, but only moving an inch before I hit yet another wall. Any advice would be greatly appreciated, I'm already so grateful for the time you've put in thus far @CruzMolina !

**Comment by CruzMolina** [comment]
No problem @RaynHarr !

I should have clarified, that compilation error you saw at the bottom of your screenshot has to do with a missing semi-colon at the end of a statement in the smart contract you're trying to migrate.

I was more just trying to troubleshoot why truffle isn't working for you globally once you `npm i -g truffle`.

I'm assuming you've taken a look at the pet shop tutorial (https://truffleframework.com/tutorials/pet-shop)?

**Comment by RaynHarr** [comment]
@CruzMolina Ahh yes, a true newb mistake. I also ran into another issue where the tutorial was having me name a function the same as the contract it resides in, which apparently Solidity doesn't allow anymore? I think I just need to find a better tutorial. I appreciate your walking me through this. Cheers!

**Comment by CruzMolina** [comment]
Hmm, I believe the tutorial I linked has the contract code updated to not include a function of the same name. Maybe it's missing the expected constructor function for solidity 0.5.0 and above. I'll take a look.

Thanks for not giving up with this! This is valuable feedback. We really want to make it as easy as possible for newcomers to pick things up and get started.

**Comment by RaynHarr** [comment]
Oh no! I meant the DAPP University tutorial I've been going through, I haven't walked through the entirety of the link you sent, I will give that a try and let you know how it goes!

**Comment by CruzMolina** [comment]
Ah, I wondered that. Yeah, I just tested the tutorial code and it compiles fine on my end. Let me know if it's otherwise on yours.

**Comment by RaynHarr** [comment]
ok @CruzMolina so I was moving along swimmingly until I hit the 'truffle test' command where I ran into this error. I've done everything up to this point that the instructions asked. Any ideas?
![Screen Shot 2019-04-02 at 10 33 42 PM](https://user-images.githubusercontent.com/39592448/55448921-96cdc080-5597-11e9-8024-ca40ba50d21d.png)

**Comment by CruzMolina** [comment]
@RaynHarr do you have Ganache running in the background?

**Comment by RaynHarr** [comment]
Ay aya ay, another embarrassing mistake. Ya looks like it crashed on me in the background, I had it going for about a week so I'm not surprised. Would have helped to check to before throwing up another issue on here. Thanks @CruzMolina !

**Comment by RaynHarr** [comment]
Ok, I think I've scrubbed all the newb errors up to this point. I've gotten the page up and running with all the dog pictures, however when hitting the adopt button, I'm getting these errors:
![Screen Shot 2019-04-03 at 6 54 16 PM](https://user-images.githubusercontent.com/39592448/55518437-0f895700-5642-11e9-86f5-57048009867f.png)
This look familiar?

**Comment by CruzMolina** [comment]
What's your `truffle-config` setting? Are you using `truffle console`, `truffle develop`, do you have Ganache running in the background? Metamask connected to the proper network?

**Comment by RaynHarr** [comment]
Ganache is running, Metamask hooked to port 7545, i'm using `npm run dev`. Truffle-config was untouched by me, but is showing same as metamask network:
![Screen Shot 2019-04-04 at 12 52 46 AM](https://user-images.githubusercontent.com/39592448/55530581-aa9b2480-5674-11e9-902c-1fcf34f6cf23.png)

**Comment by CruzMolina** [comment]
Ah, so I believe you need to specify Metamask to connect to `network_id` 5777 (Ganache's default) in the Metamask settings somewhere.

If that doesn't work, try changing the `truffle-config.js` `network_id` to 5777 instead of `"*"`. (This shouldn't be the problem though).

Oh, so this probably means we need to update the Metamask screenshots to the new UI!

**Comment by RaynHarr** [comment]
Hmm I'm getting the same error after trying both of those solutions. Is it related that my URL is 'localhost:3000' and not 127.0.1.7545 (shootin' in the dark here hahah)

**Comment by RaynHarr** [comment]
Also, I'm using the Brave browser, not sure if that has any significance...

**Comment by CruzMolina** [comment]
Hmm, no the local server being run on 3000 shouldn't be an issue.

With Ganache running, you could try doing a `migrate --reset`. Might simply be that you have artifact files that were migrated to an older instance/network of Ganache that you've since cleared (would happen by just closing down Ganache).

**Comment by RaynHarr** [comment]
Ok! Slowly but surely, truffle migrate --reset worked. but now Im getting a failed transaction:
![Screen Shot 2019-04-04 at 1 26 16 PM](https://user-images.githubusercontent.com/39592448/55575762-a9eaa880-56dd-11e9-9ece-897708a73338.png)
![Screen Shot 2019-04-04 at 1 28 32 PM](https://user-images.githubusercontent.com/39592448/55575767-ad7e2f80-56dd-11e9-907e-e00210fc371b.png)

**Comment by CruzMolina** [comment]
Hmm, hard to say without seeing your completed contract code.

Can you make sure your contract code is the same as the tutorials? I'm also assuming you were able to import your Ganache wallet key correctly and have ether to transact with.

**Comment by RaynHarr** [comment]
Ok, I did it finally! I'm not entirely sure what the fix was, I'm pretty sure it had to do with my Metamask setup though. Somewhere between me switching to the main network and back to 7545 and selecting this Account 2 that I'm fairly certain wasn't there prior. 
![Screen Shot 2019-04-04 at 3 18 37 PM](https://user-images.githubusercontent.com/39592448/55582305-26d14e80-56ed-11e9-87b2-089c5fe99cf3.png)
Didn't touch the code really, left Ganache alone, and my Account1 had Ether in it the entire time. Regardless this is has been a really good lesson on how everything interacts with each other, I appreciate the hand-holding until the end!

**Comment by CruzMolina** [comment]
No problem, congrats!

**Comment by alexandreValente** [comment]
Hi to all,

don't know if this is a truffle init issue but I get this...
When I try to migrate my Token smart contract (using Openzeppelin ERC20) I want to migrate using a custom script for initializing constructor parameter but I get stuck somewhere:

2_initial_migration.js
======================

   Deploying 'myToken'
   -------------------------
Error: Error: Error:  *** Deployment Failed ***

"myToken" hit a require or revert statement somewhere in its constructor. Try:
   * Verifying that your constructor params satisfy all require conditions.
   * Adding reason strings to your require statements.

    at Object.run (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.25 (core: 5.0.25)
Node v10.15.3

>>> FYI I can't find webpack anywhere nor truffle-migrate (locally or unders /usr/lib/...)
>>> I have upgraded to Truffle 5.0.25 and I got this issue already with previous installed version (5.0.19)
and I use Node v10.15.3 while coding in Ubuntu Virtual machine with Virtual Box.
>>>> In this case I use Ganache Gui (or cli depends on which VM i work).

>>> This is the constructor of myToken...

    constructor (uint _quantity, uint _price, uint _ethconv, uint _fees, address payable _codex, address payable _to) public {

        owner =  msg.sender;
        codex = _codex;
        quantity = _quantity;
        price = _price;
        ethconv = _ethconv;
        seller = _to;
        fees = _fees;
        
        initialSupply = _quantity;
        ethPrice = _price * _ethconv;
        
        transfer(msg.sender, initialSupply);
    }

>>>> And this is the migration script:

var myToken = artifacts.require("myToken");

let quantity = 100;
let price = 50;
let ethconv = 1; 
let fees = 45;

owner = "0xbFe32eD630d3dBEFFa7Fa1dc38aA3108B8df840c";
codex = "0x36373E9d3A70c971D4D04b09697DA7d337204CDa";
seller = "0x3F3dEeA4877D97c98f610b5BE580DdA83dBC5C36";


module.exports = function(deployer) {
	deployer.deploy(myToken, quantity, price, ethconv, fees, codex, seller, {from: owner});
};

**Comment by vinay1011998** [comment]
> I had a similar problem. I ran `npm i -g truffle` and then when I tried to run `truffle init` I got an error: `zsh: command not found: truffle`. What solved it for me is to create a local `node_modules` with truffle installed in it, and then run that copy.
> 
> 1. run `npm init` and make a new npm project
> 2. run `npm i truffle`
> 3. run `./node_modules/.bin/truffle init` and it should work
> 
> unfortunately, with this method, you'd have to call all commands by prepending `./node_modules/.bin/truffle` to the command

can you tell  me how to make a new npm project

**Comment by danielrussellLA** [comment]
@vinay1011998 I hope this answers your question: First you'll need to install nodejs at https://nodejs.org/en/. I would go for the LTS version.  Once installed, go into a folder and type `npm init` and hit enter a bunch of times on the prompts. There you go - you've created a new npm project. You'll see that two things have been created in your folder: a `package.json` file and a `node_modules` folder. At that point you can install truffle with `npm i truffle --save`. then run `./node_modules/.bin/truffle init` to start truffle at that point

**Comment by danielrussellLA** [comment]
> > I had a similar problem. I ran `npm i -g truffle` and then when I tried to run `truffle init` I got an error: `zsh: command not found: truffle`. What solved it for me is to create a local `node_modules` with truffle installed in it, and then run that copy.
> > 
> > 1. run `npm init` and make a new npm project
> > 2. run `npm i truffle`
> > 3. run `./node_modules/.bin/truffle init` and it should work
> > 
> > unfortunately, with this method, you'd have to call all commands by prepending `./node_modules/.bin/truffle` to the command
> 
> can you tell me how to make a new npm project

@vinay1011998 I hope this answers your question: First you'll need to install nodejs at https://nodejs.org/en/. I would go for the LTS version. Once installed, go into a folder and type npm init and hit enter a bunch of times on the prompts. There you go - you've created a new npm project. You'll see that two things have been created in your folder: a package.json file and a node_modules folder. At that point you can install truffle with npm i truffle --save. then run ./node_modules/.bin/truffle init to start truffle at that point

**Comment by harshmamgai** [comment]
> 
> 
> It looks to me like truffle wasn't properly installed (i.e., an npm issue). Do an `npm uninstall -g truffle` and then an `npm install -g truffle` and see if that solves it.

please use **truflle init --force**  it will resolve your problem thank me later

**Comment by AhmadKarim72** [comment]
![Screen Shot 2022-05-20 at 1 17 56 AM](https://user-images.githubusercontent.com/90279005/169455724-7e99b4ae-5e06-452d-9660-5595d34ae4b8.png)
i keep getting this error everytime I try to download truffle
