### ISSUE TITLE
Support synchronous testing of transactions

### ISSUE THREAD

**Issue by tymat** [ConsenSys/truffle#5]
Given a Solidity code that looks like this:

```
contract TestContract
   address public addr;
   function setter(address a) {
      addr = a;
   }
}
```

We would get:

```
TestContract.at(TestContract.deployed_address).setter(val).sendTransaction({from: caller})
```

and

```
TestContract.at(TestContract.deployed_address).addr.call()
```

It would be nice to have a way to be able to synchronously test this by making the test framework determine the tx_blocknumber where the transaction was created then wait a few blocks until such that current_blocknumber > (tx_blocknumber + number) to ensure that the transaction commits to TX storage and be able to make assertions on the results.  

There will be situations where the value of addr can be changed by other contracts or EOAs and we would like to be able to elegantly test these different cases.

**Comment by tymat** [comment]
See this for our rationale:

https://github.com/LeastAuthority/ethereum-analyses/blob/master/GasEcon.md#predictability

**Comment by tcoulter** [comment]
Hi @tymat. If I understand what you wrote correctly, this is already built in. Truffle uses [Pudding](https://github.com/ConsenSys/ether-pudding) under the hood, which makes ABI functions and sendTransaction() not call their callback until the transaction has been processed. The syntax is different than your example, but the effect is the same. Pudding uses promises to allow you to write the following:

```coffeescript
val = "..." # some address
test = TestContract.at(TestContract.deployed_address)
test.setter(val, {from: caller}).then (tx) ->
  # This code block won't be executed until the transaction tx has been processed.
  # Note: The next line returns a promise.
  test.addr.call()
.then (addr) ->
  assert.isEqual(addr, val)
```

This should produce the effect you're looking for. Let me know if I misunderstood.

**Comment by tcoulter** [comment]
The function within Pudding that does exactly what you described is here: https://github.com/ConsenSys/ether-pudding/blob/master/src/pudding.coffee#L100

**Comment by tymat** [comment]
@tcoulter Thanks.  That seems to work.  Is there a way to set the timeout values?

**Comment by tcoulter** [comment]
Ya, that's a feature of mocha. There are three different scopes the timeouts can apply to. Consider this example:

```coffeescript
contract "TestContract", (accounts) ->
  # Each test has a timeout of ten seconds.
  @timeout(10000) 

  before "do something before", (done) ->
    # This before() hook has a timeout of 15 seconds.
    @timeout(15000)

  it "should test something", (done) ->
    # This test has a timeout of 30 seconds.
    @timeout(30000)

  it "should do something else", (done) ->
    # This test only has a timeout of 10 seconds, based on the timeout above.
```
