### ISSUE TITLE
truffle test doesn't work in demo

### ISSUE THREAD

**Issue by taoeffect** [ConsenSys/truffle#54]
Same error as here: https://github.com/ConsenSys/dao-wars/issues/1

Edit: to be clear, by "demo" I mean what's created by `truffle init`.

**Comment by tcoulter** [comment]
@taoeffect Are you running an RPC client? I think some of the latest changes to truffle have squelched an error stating your ethereum client of choice (eth, geth, pyethereum, testrpc, ethersim) must be running.

**Comment by taoeffect** [comment]
@tcoulter That's probably the problem. I wasn't sure from the description of Ether Pudding whether it was a replacement for the RPC clients or not. Can you clear up what the difference is?

I'll try running an RPC client and see if that fixes the problem (don't want to try geth as it's slow and I don't remember how to run it with a fake chain). I'm going to be using Truffle during a [createathon](http://www.universalincome.org/) today and over the weekend, here's hoping we can get it to work on all the machines!

**Comment by tcoulter** [comment]
I just got done with DEVCON here in london (and my flight's out early in the morning) but let me know how I can help!

**Comment by taoeffect** [comment]
> but let me know how I can help!

Sure! It would help if you could explain in simple terms what the difference/roles are between Ether Pudding and EtherSim/testrpc. :)

(I'd dive into the details myself, but I'm running out of time to get out the door and drive to SF for the createathon!)

**Comment by tcoulter** [comment]
EtherPudding is a contract abstraction on top of web3's contract abstraction. The readme should do a pretty good job of explaining it: https://github.com/ConsenSys/ether-pudding . In case it doesn't, the main features are 1) Promises, for clean code, and 2) ability to manage your app's control flow synchronized with the network (i.e., you don't get your callback until your transaction is mined). There are a few other features, but they're tangential.

TestRPC and Ethersim are two solutions to the same problem (both of which I have contributed heavily). That problem is a fast chain to develop on: waiting 17 seconds per transaction to see if your code works kills productivity. So both of these projects run an Ethereum VM without mining or network and process transactions immediately, simulating the real effects of the blockchain, but much faster. TestRPC is written in Python, Ethersim in JS. 

I'm switching my efforts to Ethersim as the JS solution seems to be more stable (at least, my command of JS is greater). They're nearly feature equivalent, though Ethersim lags behind a few RPC calls. I hope to fill those out soon.

**Comment by taoeffect** [comment]
Awesome, thanks so much for that explanation! That's what I thought but I also got confused by hearing/seeing mentions of `solc` being written in JavaScript and thinking that maybe that meant that we didn't need EtherSim and projects like it anymore. I stand corrected. :)

> I'm switching my efforts to Ethersim as the JS solution seems to be more stable (at least, my command of JS is greater). They're nearly feature equivalent, though Ethersim lags behind a few RPC calls. I hope to fill those out soon.

Great! I like that EtherSim can be run standalone, because currently the situation with having it as a dependency in Embark is [kindof a mess](https://github.com/iurimatias/embark-framework/issues/99#issuecomment-156343406). EtherSim still has [its own related problems on OS X](https://github.com/iurimatias/EtherSim/issues/2) with outdated dependencies.

**Comment by tcoulter** [comment]
@taoeffect Has Iuri updated npm? If you install Ethersim from source, you'll get the updated version with my PRs accepted which fix the OS X install issues:

```
$ git clone https://github.com/iurimatias/EtherSim.git
$ cd EtherSim
$ git checkout develop && git pull
$ npm install
$ ./bin/ethersim -p 8545
```

**Comment by taoeffect** [comment]
@tcoulter EtherSim from npm still tries to install an outdated `secp256k1`, causing it to fail:

```
ethersim/node_modules/ethereumjs-block/node_modules/secp256k1

> secp256k1@1.1.4 install /usr/local/lib/node_modules/ethersim/node_modules/ethereumjs-vm/node_modules/secp256k1
```

The `develop` copy per your instructions has the correct version and therefore installed, but running `truffle test` caused it to throw an exception:

```
-> % ./bin/ethersim -p 8545
EtherSim v0.1.6

Available Accounts
==================
0x1a9dc2ad31f3fdf575479760980b242d073ee149
0xd13493e9d590ba763c202ab4fbe4ab17978cda32
0xbce16ecae7407ac3e852b8d8ea088746e357dc82
0x6d17d3b407ff990279cd852c5fe4805523cdc293
0xba88351daf7a545becf4fccd1555e2750b445c9c
0x7ab301af6a5d37c09b1264d46a42c78288a339ff
0xe0c1976e9e9350986aa942b1176f6d23e0db90f8
0xfb61aa6b35754d8779f989e50e616b0ab4d11662
0x52e18c7cda62b91cbeafd52fbd0561720e2bd804
0xa2d916f6f7490ab9f1aa5e444ef078eb7478b23b

Listening on localhost:8545
eth_accounts
eth_coinbase
eth_sendTransaction
eth_newBlockFilter
eth_getFilterChanges
/Users/greg/Ethereum/frameworks/EtherSim/lib/blockchain.js:313
    queued.callback(err, result);
           ^

TypeError: queued.callback is not a function
    at intermediary (/Users/greg/Ethereum/frameworks/EtherSim/lib/blockchain.js:313:12)
    at /Users/greg/Ethereum/frameworks/EtherSim/lib/blockchain.js:418:7
    at Object.async.eachSeries (/Users/greg/Ethereum/frameworks/EtherSim/node_modules/async-eventemitter/node_modules/async/lib/async.js:130:20)
    at VM.AsyncEventEmitter.emit (/Users/greg/Ethereum/frameworks/EtherSim/node_modules/async-eventemitter/lib/AsyncEventEmitter.js:42:9)
    at afterBlock (/Users/greg/Ethereum/frameworks/EtherSim/node_modules/ethereumjs-vm/lib/runBlock.js:55:10)
    at /Users/greg/Ethereum/frameworks/EtherSim/node_modules/ethereumjs-vm/lib/runBlock.js:179:9
    at /Users/greg/Ethereum/frameworks/EtherSim/node_modules/ethereumjs-vm/lib/cache.js:136:7
    at /Users/greg/Ethereum/frameworks/EtherSim/node_modules/async/lib/async.js:52:16
    at iterate (/Users/greg/Ethereum/frameworks/EtherSim/node_modules/async/lib/async.js:260:24)
    at Object.async.forEachOfSeries.async.eachOfSeries (/Users/greg/Ethereum/frameworks/EtherSim/node_modules/async/lib/async.js:281:9)
```

`truffle test` got as far as:

```
-> % truffle test
Using environment test.
Compiling contracts...


  Contract: Example
```

**Comment by tcoulter** [comment]
Interesting. Not necessarily sure why at the moment, never had that issue
myself. Currently in bed, however, so will have to take a look at another
time. If all else fails fall back on the TestRPC.

**Comment by taoeffect** [comment]
FYI, just verified that this works on TestRPC aka [eth-testrpc](https://github.com/ConsenSys/eth-testrpc).

So, since this is not an intrinsic Truffle issue I'm closing this, and I opened a corresponding EtherSim issue: https://github.com/iurimatias/EtherSim/issues/6
