### ISSUE TITLE
truffle bootstrap items should be concatenated before other js file contents

### ISSUE THREAD

**Issue by jmadan** [ConsenSys/truffle#55]
final app.js generated in build folder has the following concatenated in the very end 

// Added by Truffle bootstrap.
window.web3 = new Web3();
window.web3.setProvider(new Web3.providers.HttpProvider("http://localhost:8545"));
Pudding.setWeb3(window.web3);
Pudding.load([UserContract], window);

this throws the Reference error of web3 undefined if you try to access web3 object in any of your JS files.

**Comment by robmyers** [comment]
You can address this by only calling web3 starting in window.onload().

**Comment by tcoulter** [comment]
Thanks @robmeyers. Closing.
