### ISSUE TITLE
Possible mistake in front page?

### ISSUE THREAD

**Issue by Smithgift** [ConsenSys/truffle#57]
Is .isTrue() the function you want in this example? It seems it should be .equal()

```js
assert.isTrue(20000, my_balance, "I was not given 20000 on contract creation!");
```

**Comment by tcoulter** [comment]
Looks like this has has been fixed in the docs. Since this is a very old ticket, I'm going to close it. Please check out the [Truffle Gitter](https://gitter.im/ConsenSys/truffle) or file a new ticket if you have issues. Cheers!
