### ISSUE TITLE
web3 appears to be missing.

### ISSUE THREAD

**Issue by Smithgift** [ConsenSys/truffle#58]
web3 does not appear to be present in truffle console or truffle test. Pudding.web3 is available, just not the original web3.

**Comment by tcoulter** [comment]
Marking this to be explored for milestone 0.4.0. Will test and see if I can reproduce.

**Comment by tcoulter** [comment]
@Smithgift web3 is definitely available for me in Truffle tests. Can you tell me more about the issues you're seeing here so I can investigate?

**Comment by tcoulter** [comment]
Reproduced. Fixing now.
