### ISSUE TITLE
create:contract should automatically add to the deploy list

### ISSUE THREAD

**Issue by tcoulter** [ConsenSys/truffle#6]
or perhaps add a `--deploy` flag? Please weigh in with comments on what the default behavior should be.

**Comment by christianlundkvist** [comment]
I think it should automatically add to the deploy list.

**Comment by drborges** [comment]
First things first: great job @tcoulter, truffle is a big step towards making Ethereum and its whole ecosystem accessible by anyone.

I'd ask how often does one create contracts that shouldn't be added to the deploy list?

If I find myself creating contracts and manually adding them to the deploy list very often then @christianlundkvist's suggestion makes a lot of sense.

**Comment by tcoulter** [comment]
This is no longer valid in Truffle 2.0. You now have way more control of your deployment. Try it out!
