### ISSUE TITLE
Allow RPC Configuration for Deployment

### ISSUE THREAD

**Issue by josiahwood** [ConsenSys/truffle#64]
I would like to have a configuration property in the `app.json` file that allows customization of the gas used to deploy contracts.  This is especially useful for contracts that require more gas than the hard-coded value of 3141592.

**Comment by tcoulter** [comment]
I think configuring the value is good. However, I don't think you can have a gas limit higher than 3141592. If you try to deploy those contracts to the live network they won't be accepted.

**Comment by josiahwood** [comment]
Oh, ok.  Hmm, I guess I have some refactoring to do then.

**Comment by tcoulter** [comment]
I'm going to co-opt this ticket and turn it into these features:

[ ] Allow `gasLimit` configuration for deployment
[ ] Allow `gasPrice` configuration for deployment
[ ] Allow `from` address configuration for deployment

Scheduled for 0.4.0 (next release).
