### ISSUE TITLE
Truffle is probably producing transpiled code that fails in Firefox

### ISSUE THREAD

**Issue by johnmcdowall** [ConsenSys/truffle#66]
If you take a look at `ether-pudding`'s build output on line 40:

https://github.com/ConsenSys/ether-pudding/blob/master/build/ether-pudding.js#L40

You'll see a `Symbol.iterator` - this is not supported in Firefox as of yet. 

I think the solution is that Babel needs to be called here https://github.com/ConsenSys/truffle/blob/master/lib/processors/babel.es6#L6 with the option of` 'stage': 0` added to the options hash. 

Trying to test it out but can't get Truffle to build locally at the moment.

**Comment by tcoulter** [comment]
Will add this anyway. I'd rather compile completely down to ES5, and if this is the way to do it, then that's what we should do.

I've always wondering what that Symbol.iterator stuff is...

**Comment by tcoulter** [comment]
Alright, with `stage: 0` set `Symbol.iterator` still exists in the code, but it looks like they add a shim for it, using this code:

```
/**
 * Copyright 2013-2015, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 * @providesModule getIteratorFn
 * @typechecks static-only
 */

'use strict';

/* global Symbol */
var ITERATOR_SYMBOL = typeof Symbol === 'function' && Symbol.iterator;
var FAUX_ITERATOR_SYMBOL = '@@iterator'; // Before Symbol spec.

/**
 * Returns the iterator method function contained on the iterable object.
 *
 * Be sure to invoke the function with the iterable as context:
 *
 *     var iteratorFn = getIteratorFn(myIterable);
 *     if (iteratorFn) {
 *       var iterator = iteratorFn.call(myIterable);
 *       ...
 *     }
 *
 * @param {?object} maybeIterable
 * @return {?function}
 */
function getIteratorFn(maybeIterable) {
  var iteratorFn = maybeIterable && (
    (ITERATOR_SYMBOL && maybeIterable[ITERATOR_SYMBOL] || maybeIterable[FAUX_ITERATOR_SYMBOL])
  );
  if (typeof iteratorFn === 'function') {
    return iteratorFn;
  }
}

module.exports = getIteratorFn;
```

I haven't spent any time trying to grok what it does, but I'll try removing `stage: 0`, reproducing the firefox issue and then putting it back. If it fixes firefox, it goes in!

**Comment by tcoulter** [comment]
Regarding Pudding, es6 has been completely removed from the codebase, and so `Symbol` doesn't even show up in the bundled code (it's even using webpack now): https://github.com/ConsenSys/ether-pudding/blob/master/dist/ether-pudding.js

I'm not necessarily sure if that applies to Truffle's default build system and how it handles other es6 files. That said, that build system is being phased out, and people should use their own build system instead. I'm considering this one closed/fixed.
