### ISSUE TITLE
Contract works under embark but not under truffle?

### ISSUE THREAD

**Issue by mjackson001** [ConsenSys/truffle#68]
I have a strange situation where the same RPC eth_call request goes out from embark and from truffle to the same function in the same contract (deployed at different addresses because one uses the embark blockchain and the other testrpc, but that's the only difference).  The embark call returns a result while the other returns zero.  I see differences in the HTTP requests going over the RPC port, but I don't know why / if that explains the difference.  I'm filing this as a possible truffle bug - could the Connection: close vs keep-alive be causing the issue?

Function in contract:

function fn(int x) constant returns (int result);

This is being called from truffle (pudding) using:

Contract.fn.call(4000000.0, {from: coinbase}).then(function(res) {
	console.log("result=" + res.toString(10));
});

Works (embark):

POST / HTTP/1.1
Host: localhost:8101
Connection: keep-alive
Content-Length: 252
Origin: http://localhost:8000
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Content-type: application/json
Accept: */*
Referer: http://localhost:8000/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x0a181d935007b7bfe2720091f33c628b1bfcecb9","data":"0xd271b06700000000000000000000000000000000000000000000000000000000003d0900","from":"0x3c9601da93841f13f48f7c1f13a3f5950c1cd00f"},"latest"],"id":4}

HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://localhost:8000
Content-Type: application/json
Vary: Origin
Date: Thu, 24 Dec 2015 02:53:59 GMT
Content-Length: 103

{"id":4,"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000152736"}

Doesn't work (truffle):

POST / HTTP/1.1
User-Agent: node-XMLHttpRequest
Accept: */*
Content-Type: application/json
Host: localhost:8545
Content-Length: 252
Connection: close

{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0x82a978b3f5962a5b0957d9ee9eef472ee55b42f1","to":"0xc305c901078781c232a2a521c2af7980f8385ee9","data":"0x8e6f235300000000000000000000000000000000000000000000000000000000003d0900"},"latest"],"id":2}

HTTP/1.0 200 OK
Server: BaseHTTP/0.3 Python/2.7.6
Date: Thu, 24 Dec 2015 02:52:01 GMT
Content-type: application/json-rpc
Content-length: 107
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *

{"jsonrpc": "2.0", "result":"0x0000000000000000000000000000000000000000000000000000000000000000", "id": 2}

**Comment by mjackson001** [comment]
After hours of debug, it turns out when copying the contract I had renamed it without renaming the constructor.  Certain dependencies were not being initialized correctly.  Wow, talk about learning the hard way.

**Comment by tcoulter** [comment]
Ya, I wish there were an easier way for truffle to detect the issue. There
is a way, but it's not easy. Although I suppose we could just grep the file
contents and see if the name we're expecting at least exists. I'd love help
if you're interested in tackling that issue.

**Comment by mjackson001** [comment]
I would love to be able to contribute where I can.  I have to confess to being a newb at Ethereum - I'm still learning the inner workings.  Although I've been following the project and it's ecosystem since its inception.

Mark
