### ISSUE TITLE
Run individual tests

### ISSUE THREAD

**Issue by oed** [ConsenSys/truffle#7]
There should be a way to run only specific tests.
An interface for this could be:
`truffle test` - run all tests
`truffle test testname` - run specific test, where testname is a file in the test/ folder called testname.coffee

**Comment by tymat** [comment]
This would be very useful.  Additionally it would be nice to be able to select different tests to run in sequence i.e.

```
truffle test contract1 contract2 contract3
```

**Comment by tcoulter** [comment]
This has partially been added, and you'll see it in the latest release coming today. 

```
$ truffle test ./path/to/test/file
```
