### ISSUE TITLE
Integrate new version of Solidity(0.1.6 to 0.2.0-1)

### ISSUE THREAD

**Issue by agatsoh** [ConsenSys/truffle#75]
The new version of solidity(0.2.0-1) has already been uploaded to the npm and it would be nice if truffle integrates it as one of its submodules so that all solidity programs can  run as usual.The current version of solidity on truffle is 0.1.6 and the new version in npm is 0.2.0-1.

**Comment by tcoulter** [comment]
Apparently, when I run `npm install solc`, I get `0.1.6`. Do you know if 0.2.0-1 is somehow marked to not upgrade?

**Comment by agatsoh** [comment]
When you install globally you get the latest version, when you install locally you get the earlier version, even i observed it. I have no idea whether it has been marked for an upgrade or not.

**Comment by u2** [comment]
https://github.com/ConsenSys/truffle/pull/78

**Comment by tcoulter** [comment]
This is done. Closing!
