### ISSUE TITLE
Output ABI for non-deployed contracts

### ISSUE THREAD

**Issue by jgostylo** [ConsenSys/truffle#83]
I have my project setup in hub/spoke fashion.  All of the projects live in a single file and only one of them is deployed.  I want to have access to the ABI for the non-deployed contracts in my test and app environment.

I assume that this would be possible if the contracts were in separate files because that outputs <contract>.sol.js for each contract deployed or no but that does not work for my use case.  I want some functionality of my hub to only be accessible when called from the spoke contract (as a way of identity management) and that would require a circular import in solidity which does not seem to work.

**Comment by jgostylo** [comment]
Pull request submitted: https://github.com/ConsenSys/truffle/pull/86

**Comment by tcoulter** [comment]
Closing this one in favor of #204. This feature is definitely still on our list. Thanks!
