### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by raymondcarl** [ConsenSys/truffle#87]
Hi, very novice user here running Ubuntu 14.04 64 bit.
Installation stops after a few minutes with this error:

>  npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/truffle/node_modules/lodash/internal/arrayCopy.js'
> npm ERR! If you need help, you may report this log at:
> npm ERR!     <http://github.com/isaacs/npm/issues>
> npm ERR! or email it to:
> npm ERR!     <npm-@googlegroups.com>

I'm not sure if this is an issue with NPM or truffle.  I checked the referenced error log provided at the end of the installation and it is empty.  The NPM installation seemed to go ok.

Thanks!

**Comment by raymondcarl** [comment]
Just to add one issue that has come up when I've had some issues trying with other frameworks.  Could this be caused by install npm using sudo?

**Comment by tcoulter** [comment]
I looks like it might have something to do with your version of node. What version of node are you using?

> npm WARN This failure might be due to the use of legacy binary "node"

I'd recommend upgrading to the latest and seeing if you have the same issue.

**Comment by raymondcarl** [comment]
Yep, that was it.  I think the version of Node that comes in the standard repository is to outdated for npm.  I went to the github site for Node and installed that version and then Truffle installed ok.  Thanks!

**Comment by lin520chong** [comment]
When npm install -g truffle, i had a error.Has anybody can given me a help? thanks!

> node-sass@3.7.0 install /usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/node_modules/node-sass/vendor/linux-x64-11/binding.node
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/truffle/node_modules/babel-preset-stage-2/node_modules/babel-plugin-transform-object-rest-spread/node_modules/babel-runtime/node_modules/core-js'
npm ERR! error rolling back  babel-preset-stage-2@6.5.0 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/truffle/node_modules/babel-preset-stage-2/node_modules/babel-plugin-transform-object-rest-spread/node_modules/babel-runtime/node_modules/core-js']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/truffle/node_modules/babel-preset-stage-2/node_modules/babel-plugin-transform-object-rest-spread/node_modules/babel-runtime/node_modules/core-js' }

> node-sass@3.7.0 postinstall /usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/node_modules/node-sass
> node scripts/build.js

"/usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/node_modules/node-sass/vendor/linux-x64-11/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/marvin/demo/npm-debug.log
npm ERR! not ok code 0
