### ISSUE TITLE
Compilation Error: Expected identifier uint[2][] memory arrayOfPairs = new uint[2][](size);

### ISSUE THREAD

**Issue by MeLoco1** [ConsenSys/truffle#91]
I took example contract from here http://solidity.readthedocs.org/en/latest/types.html?highlight=type%20conversion#arrays
`contract ArrayContract {
  uint[2**20] m_aLotOfIntegers;
  // Note that the following is not a pair of arrays but an array of pairs.
  bool[2][] m_pairsOfFlags;
  // newPairs is stored in memory - the default for function arguments
  function setAllFlagPairs(bool[2][] newPairs) {
    // assignment to a storage array replaces the complete array
    m_pairsOfFlags = newPairs;
  }
  function setFlagPair(uint index, bool flagA, bool flagB) {
    // access to a non-existing index will throw an exception
    m_pairsOfFlags[index][0] = flagA;
    m_pairsOfFlags[index][1] = flagB;
  }
  function changeFlagArraySize(uint newSize) {
    // if the new size is smaller, removed array elements will be cleared
    m_pairsOfFlags.length = newSize;
  }
  function clear() {
    // these clear the arrays completely
    delete m_pairsOfFlags;
    delete m_aLotOfIntegers;
    // identical effect here
    m_pairsOfFlags.length = 0;
  }
  bytes m_byteData;
  function byteArrays(bytes data) {
    // byte arrays ("bytes") are different as they are stored without padding,
    // but can be treated identical to "uint8[]"
    m_byteData = data;
    m_byteData.length += 7;
    m_byteData[3] = 8;
    delete m_byteData[2];
  }
  function addFlag(bool[2] flag) returns (uint) {
    return m_pairsOfFlags.push(flag);
  }
  function createMemoryArray(uint size) returns (bytes) {
    // Dynamic memory arrays are created using `new`:
    uint[2][] memory arrayOfPairs = new uint[2][](size);
    // Create a dynamic byte array:
    bytes memory b = new bytes(200);
    for (uint i = 0; i < b.length; i++)
      b[i] = byte(i);
    return b;
  }
}`

On attempt to compile the contract I get an error:
Compiling ./contracts/ArrayContract.sol...
Error compiling ./contracts/ArrayContract.sol:

:30:45: Error: Expected identifier
        uint[2][] memory arrayOfPairs = new uint[2][](size);

This contract successfully compiled here: https://www.etherchain.org/solc

--vtruffle --version
Truffle v0.3.1 - a development framework for Ethereum

 testrpc
EthereumJS TestRPC v0.1.1

**Comment by tcoulter** [comment]
I'm surprised this compiles:
```
uint[2][] memory arrayOfPairs = new uint[2];
```
Unless that's a bad copy paste. Because it looks like you're trying to instantiate a new single-dimensional array and store it in a variable defined as a multi-dimensional array.

**Comment by tcoulter** [comment]
But - Solidity arrays are weird, so I wouldn't be surprised if I'm wrong.

**Comment by MeLoco1** [comment]
This copy pasted the output from the command line. In contract it looks like this:

    function createMemoryArray(uint size) returns (bytes) {

    // Dynamic memory arrays are created using `new`:
    uint[2][] memory arrayOfPairs = new uint[2][](size);

    // Create a dynamic byte array:
    bytes memory b = new bytes(200);
    for (uint i = 0; i < b.length; i++)
      b[i] = byte(i);
    return b;
    }


It is an example from solidity array specification
http://solidity.readthedocs.org/en/latest/types.html?highlight=type%20conversion#arrays

**Comment by MeLoco1** [comment]
That's really an issue. Check the contract:
 `
    contract MultiAssetContract {

    struct Asset {
        bytes32 symbol;
        uint8 baseUnit;
        bytes32 name;
        bytes32 description;
        mapping (address => uint) index;
        address[] holders;
        uint[] amounts;
    }
    
    mapping(bytes32 => uint) public assetIndex;
    Asset[] public assets;

    function issueAsset() returns (bool) {
        bytes32 symbol = "LCC";

        if (assetIndex[symbol] > 0) {
            return false;
        }
        uint pos = assets.length++;

        assets[pos] = Asset({
            symbol: symbol,
            holders: new address[](2),
            amounts: new uint[](2),
            name: "Coin",
            description: "My coins",
            baseUnit: 1
        });

        return true;
    }
    }
`

it successfully has been compiled in https://chriseth.github.io/browser-solidity/
and works in Ethereum network. 
However `truffle compile` fails with:

Error compiling ./contracts/MultiAssetContract.sol:

:27:26: Error: Expected identifier
            holders: new address[](2),
                         ^

**Comment by tcoulter** [comment]
My response to this has been long overdue. This compile fine now on Truffle 2.0. My guess is that since this was reported, solc has been upgraded many times, which fixed the issue. Let me know if you still run into it. Thanks!
