### ISSUE TITLE
contract data variables overwritten in build/app.js

### ISSUE THREAD

**Issue by cdetrio** [ConsenSys/truffle#95]
`truffle init` uses the MetaCoin example to build the environments/development/build/app.js file with this line at the bottom:

    Pudding.load([ConvertLib, MetaCoin], window); 

The problem is that ConvertLib and MetaCoin are both created with the MetaCoin contract_data variable because it is declared after the contract_data associated with ConvertLib, but in the same scope (and so overwrites it).

This can be fixed by putting a closure around the [ether-pudding class template](https://github.com/ConsenSys/ether-pudding/blob/master/classtemplate.es6):

```

// Factory "morphs" into a Pudding class.
// The reasoning is that calling load in each context
// is cumbersome.

(function() {

  var contract_data = {
    abi: {{ABI}},
    binary: "{{BINARY}}",
    unlinked_binary: "{{UNLINKED_BINARY}}",
    address: "{{ADDRESS}}",
    generated_with: "{{PUDDING_VERSION}}",
    contract_name: "{{NAME}}"
  };

  .....

  if (typeof module != "undefined" && typeof module.exports != "undefined") {
    module.exports = Contract;
  } else {
    // There will only be one version of Pudding in the browser,
    // and we can use that.
    window.{{NAME}} = Contract;
  }

})();

```

**Comment by tcoulter** [comment]
Great catch. This will require a change in Pudding. Not entirely sure how this sat unfound for so long.

Should have fix soon.

**Comment by tcoulter** [comment]
Should be fixed in https://github.com/ConsenSys/truffle/commit/01d0cea2e0d97410afcdb9a20a0dbcae190557c2. Can you pull from master and give it a shot?

**Comment by tcoulter** [comment]
After the changes, on my machine:

![screen shot 2016-02-25 at 1 01 23 pm](https://cloud.githubusercontent.com/assets/92629/13334245/efdf0af8-dbbf-11e5-8af8-1f95445cfe93.png)

**Comment by tcoulter** [comment]
@cdetrio I'm going to mark this as closed. Let me know if you still see the issue!
