### ISSUE TITLE
Compilation warning turns into truffle error

### ISSUE THREAD

**Issue by MrChico** [ConsenSys/truffle#96]
It turns out that this contract doesn't really do what I hoped it would, but still I would guess that allowing for warnings in compilation is a good idea.
```
contract arrayswitcher {
    address[] public oldArray;
    
    function deleteElement(uint256 index) {
        address[] newArray;
        for (uint256 i = 0; i < oldArray.length; i++) {
	        if (i!=index) {
	            newArray.push(oldArray[i]);
	        }
        }
        oldArray = newArray;
    }
}
```
Compiles with the warning: uninitialized storage pointer, but in truffle it gives error.

**Comment by tcoulter** [comment]
Fixed on master. Cheers!
