### ISSUE TITLE
Compilation fails (new string() )

### ISSUE THREAD

**Issue by HCharlanes** [ConsenSys/truffle#99]
I can find this error when using truffle (with testrpc or geth).
This error does not appear when using browser-solidity (from sol version 2.0 2015.12.10 at least it does work)
````
Error compiling ./contracts/KrakenPriceTicker.sol:

:160:35: Error: Expected identifier
        string memory abcde = new string(_ba.length + _bb.length + _bc.length + _bd.length + _be.length);
                                  ^
Compiliation failed. See above.
```
`

**Comment by silly-n** [comment]
Hi, I think solc will be bumped in 0.4 (you might as well try the pre-release, it compiles for me now, but doesn't get deployed, but that's another issue).

https://github.com/ConsenSys/truffle/issues/75
https://github.com/ConsenSys/truffle/pull/78

**Comment by tcoulter** [comment]
Fixed on master after upgrading solc.
